import express from 'express'
import BattleTrainer from '../models/BattleTrainer.js'
import {
    normalizeFormId,
    resolveEffectivePokemonBaseStats,
    resolvePokemonFormEntry,
} from '../utils/pokemonFormStats.js'

const router = express.Router()
const BATTLE_TRAINERS_CACHE_TTL_MS = 60 * 1000
const BATTLE_TRAINERS_CACHE_CONTROL = 'public, max-age=60, stale-while-revalidate=120'

let battleTrainersCache = {
    expiresAt: 0,
    trainers: [],
}

const activeBattleTrainerFilter = {
    $or: [
        { isActive: true },
        { isActive: { $exists: false } },
        { isActive: null },
    ],
}

const toSafeLevel = (value) => Math.max(1, Math.floor(Number(value) || 1))

const resolveTrainerTeamEntry = (entry = {}) => {
    const pokemon = entry?.pokemonId && typeof entry.pokemonId === 'object'
        ? entry.pokemonId
        : null
    const formId = normalizeFormId(entry?.formId || pokemon?.defaultFormId || 'normal')
    const resolvedForm = resolvePokemonFormEntry(pokemon || {}, formId)
    const resolvedImageUrl = String(
        resolvedForm?.imageUrl
        || resolvedForm?.sprites?.normal
        || resolvedForm?.sprites?.icon
        || pokemon?.imageUrl
        || pokemon?.sprites?.normal
        || pokemon?.sprites?.front_default
        || ''
    ).trim()
    const resolvedStats = resolveEffectivePokemonBaseStats({
        pokemonLike: pokemon || {},
        formId,
        resolvedForm,
    })

    return {
        pokemonId: {
            _id: pokemon?._id || entry?.pokemonId || null,
            name: String(pokemon?.name || 'Pokemon').trim() || 'Pokemon',
            imageUrl: resolvedImageUrl,
            sprites: {
                normal: resolvedImageUrl || String(pokemon?.sprites?.normal || pokemon?.sprites?.front_default || '').trim(),
                icon: String(resolvedForm?.sprites?.icon || pokemon?.sprites?.icon || resolvedImageUrl || '').trim(),
            },
            baseStats: resolvedStats,
            types: Array.isArray(pokemon?.types) ? pokemon.types : [],
            defaultFormId: formId,
        },
        level: toSafeLevel(entry?.level),
        formId,
        damagePercent: Math.max(0, Number(entry?.damagePercent) || 100),
    }
}

const normalizeTrainerRow = (entry = {}) => {
    const prizePokemon = entry?.prizePokemonId && typeof entry.prizePokemonId === 'object'
        ? entry.prizePokemonId
        : null
    const prizeItem = entry?.prizeItemId && typeof entry.prizeItemId === 'object'
        ? entry.prizeItemId
        : null

    return {
        _id: entry?._id || null,
        name: String(entry?.name || 'Trainer').trim() || 'Trainer',
        imageUrl: String(entry?.imageUrl || '').trim(),
        quote: String(entry?.quote || '').trim(),
        orderIndex: Math.max(0, Math.floor(Number(entry?.orderIndex) || 0)),
        autoGenerated: Boolean(entry?.autoGenerated),
        milestoneLevel: Math.max(0, Math.floor(Number(entry?.milestoneLevel) || 0)),
        team: (Array.isArray(entry?.team) ? entry.team : []).map(resolveTrainerTeamEntry),
        prizePokemonId: prizePokemon
            ? {
                _id: prizePokemon._id,
                name: String(prizePokemon.name || '').trim(),
                imageUrl: String(prizePokemon.imageUrl || prizePokemon.sprites?.normal || prizePokemon.sprites?.front_default || '').trim(),
            }
            : null,
        prizeItemId: prizeItem
            ? {
                _id: prizeItem._id,
                name: String(prizeItem.name || '').trim(),
                imageUrl: String(prizeItem.imageUrl || '').trim(),
            }
            : null,
        prizeItemQuantity: Math.max(1, Number(entry?.prizeItemQuantity) || 1),
        platinumCoinsReward: Math.max(0, Number(entry?.platinumCoinsReward) || 0),
        expReward: Math.max(0, Number(entry?.expReward) || 0),
        moonPointsReward: entry?.autoGenerated ? 0 : Math.max(0, Number(entry?.moonPointsReward) || 0),
    }
}

// GET /api/battle-trainers - Public list
router.get('/', async (req, res) => {
    try {
        res.set('Cache-Control', BATTLE_TRAINERS_CACHE_CONTROL)

        const now = Date.now()
        if (battleTrainersCache.expiresAt > now && Array.isArray(battleTrainersCache.trainers)) {
            return res.json({ ok: true, trainers: battleTrainersCache.trainers })
        }

        const trainerRows = await BattleTrainer.find(activeBattleTrainerFilter)
            .sort({ orderIndex: 1, createdAt: 1 })
            .populate('team.pokemonId', 'name imageUrl sprites forms.formId forms.formName forms.imageUrl forms.sprites forms.stats defaultFormId baseStats types')
            .populate('prizePokemonId', 'name imageUrl sprites')
            .populate('prizeItemId', 'name imageUrl type rarity')
            .lean()

        const trainers = trainerRows.map((entry) => normalizeTrainerRow(entry))

        battleTrainersCache = {
            trainers,
            expiresAt: now + BATTLE_TRAINERS_CACHE_TTL_MS,
        }

        res.json({ ok: true, trainers })
    } catch (error) {
        console.error('GET /api/battle-trainers error:', error)
        res.status(500).json({ ok: false, message: 'Lỗi máy chủ' })
    }
})

export default router
