import express from 'express'
import BattleTrainer from '../models/BattleTrainer.js'

const router = express.Router()

// GET /api/battle-trainers - Public list
router.get('/', async (req, res) => {
    try {
        await BattleTrainer.updateMany(
            {
                autoGenerated: true,
                moonPointsReward: { $ne: 0 },
            },
            {
                $set: { moonPointsReward: 0 },
            }
        )

        const trainers = await BattleTrainer.find({ isActive: true })
            .sort({ orderIndex: 1, createdAt: 1 })
            .populate('team.pokemonId', 'name pokedexNumber imageUrl sprites forms defaultFormId baseStats rarity types')
            .populate('prizePokemonId', 'name pokedexNumber imageUrl sprites forms defaultFormId')
            .populate('prizeItemId', 'name imageUrl type rarity')
            .lean()

        res.json({ ok: true, trainers })
    } catch (error) {
        console.error('GET /api/battle-trainers error:', error)
        res.status(500).json({ ok: false, message: 'Lỗi máy chủ' })
    }
})

export default router
