const TITLE_WORD_OVERRIDES = {
    hp: 'HP',
    ko: 'KO',
    pp: 'PP',
    crit: 'Critical',
}

const VI_WORD_OVERRIDES = {
    apply: 'ap dung',
    status: 'trang thai',
    clear: 'xoa',
    stat: 'chi so',
    stage: 'bac',
    random: 'ngau nhien',
    power: 'suc manh',
    modifier: 'dieu chinh',
    by: 'theo',
    user: 'nguoi dung',
    target: 'muc tieu',
    hp: 'HP',
    with: 'voi',
    if: 'neu',
    set: 'thiet lap',
    terrain: 'dia hinh',
    weather: 'thoi tiet',
    bind: 'troi buoc',
    recoil: 'phan sat thuong',
    heal: 'hoi mau',
    fraction: 'ti le',
    max: 'toi da',
    damage: 'sat thuong',
    never: 'khong bao gio',
    miss: 'truot',
    always: 'luon',
    crit: 'chi mang',
    rate: 'ti le',
    priority: 'uu tien',
    require: 'bat buoc',
    copy: 'sao chep',
    swap: 'hoan doi',
    steal: 'cuop',
    boost: 'tang cuong',
    move: 'chieu',
    block: 'chan',
    shield: 'la chan',
    transfer: 'chuyen',
    ignore: 'bo qua',
    use: 'su dung',
    defense: 'phong thu',
    attack: 'tan cong',
    higher: 'cao hon',
    offense: 'tan cong',
    recharge: 'hoi suc',
    force: 'ep buoc',
    faint: 'xiu',
    survive: 'song sot',
    next: 'lan tiep',
    normal: 'thuong',
    electric: 'dien',
    become: 'tro thanh',
    flavor: 'mo ta',
    only: 'chi',
    stages: 'bac chi so',
    atk: 'tan cong',
    def: 'phong thu',
    spatk: 'tan cong dac biet',
    spdef: 'phong thu dac biet',
    spd: 'toc do',
    current: 'hien tai',
    value: 'gia tri',
    from: 'tu',
    level: 'cap do',
    guards: 'la chan',
    reduction: 'giam',
    userhp: 'HP nguoi dung',
}

const OP_META_OVERRIDES = {
    apply_status: { nameEn: 'Apply Status', nameVi: 'Gay trang thai' },
    apply_status_random: { nameVi: 'Gay mot trang thai ngau nhien' },
    apply_status_if: { nameVi: 'Gay trang thai theo dieu kien' },
    always_crit: { nameVi: 'Dam bao chi mang' },
    apply_bind: { nameVi: 'Gay troi buoc theo turn' },
    average_attack_spatk_stages_with_target: { nameVi: 'Can bang bac Tan cong va Tan cong dac biet voi muc tieu' },
    average_def_spdef_stages_with_target: { nameVi: 'Can bang bac Phong thu va Phong thu dac biet voi muc tieu' },
    average_hp_with_target: { nameVi: 'Can bang HP hien tai voi muc tieu' },
    add_type_to_target: { nameVi: 'Them he cho muc tieu' },
    clear_status: { nameEn: 'Clear Status', nameVi: 'Xoa trang thai' },
    clear_status_if: { nameVi: 'Xoa trang thai theo dieu kien' },
    clear_damage_guards: { nameVi: 'Xoa la chan giam sat thuong' },
    clear_stat_stages: { nameVi: 'Xoa toan bo bac chi so' },
    clear_terrain: { nameVi: 'Xoa dia hinh' },
    copy_target_stat_stages: { nameVi: 'Sao chep bac chi so cua muc tieu' },
    crash_damage_on_miss_fraction_max_hp: { nameVi: 'Tu gay sat thuong khi hut don' },
    crit_rate: { nameVi: 'Tang ti le chi mang' },
    delayed_damage: { nameVi: 'Gay sat thuong tre sau mot so luot' },
    direct_damage_only: { nameVi: 'Chi gay sat thuong truc tiep' },
    damage_fraction_target_current_hp: { nameVi: 'Gay sat thuong theo HP hien tai cua muc tieu' },
    damage_reduction_shield: { nameEn: 'Damage Shield', nameVi: 'La chan giam sat thuong' },
    enforce_target_survive: { nameVi: 'Khong de muc tieu bi ha guc' },
    fixed_damage_from_user_level: { nameVi: 'Sat thuong co dinh theo cap do nguoi dung' },
    fixed_damage_random_user_level: { nameVi: 'Sat thuong ngau nhien theo cap do nguoi dung' },
    fixed_damage_value: { nameVi: 'Sat thuong co dinh' },
    force_switch_target: { nameVi: 'Ep muc tieu doi Pokemon' },
    force_berry_consumption: { nameVi: 'Buoc an Berry tren san' },
    force_escape_wild: { nameVi: 'Ep thoat khoi tran hoang da' },
    force_target_ko: { nameVi: 'Ha guc muc tieu ngay lap tuc' },
    heal_fraction_damage: { nameVi: 'Hoi mau theo sat thuong gay ra' },
    heal_fraction_max_hp: { nameVi: 'Hoi mau theo phan tram HP toi da' },
    heal_fraction_max_hp_if: { nameVi: 'Hoi mau theo dieu kien' },
    hp_fraction_cost_max_hp: { nameVi: 'Tieu hao HP theo phan tram toi da' },
    ignore_target_ability: { nameVi: 'Bo qua Ability cua muc tieu' },
    ignore_damage_guards: { nameVi: 'Bo qua la chan giam sat thuong' },
    ignore_target_stat_stages: { nameVi: 'Bo qua bac chi so cua muc tieu' },
    invert_target_stat_stages: { nameVi: 'Dao nguoc bac chi so cua muc tieu' },
    multi_hit: { nameVi: 'Tan cong nhieu lan' },
    never_miss: { nameVi: 'Khong bao gio truot' },
    power_modifier_if: { nameEn: 'Conditional Power Modifier', nameVi: 'Dieu chinh suc manh theo dieu kien' },
    power_modifier_by_user_hp: { nameEn: 'Power by User HP', nameVi: 'Dieu chinh suc manh theo HP nguoi dung' },
    power_modifier_random: { nameVi: 'Dieu chinh suc manh ngau nhien' },
    prevent_repeat_move: { nameVi: 'Khong cho lap lai chieu vua dung' },
    priority_mod: { nameVi: 'Dieu chinh do uu tien' },
    priority_mod_if: { nameVi: 'Dieu chinh do uu tien theo dieu kien' },
    random_heal_or_damage: { nameVi: 'Ngau nhien gay sat thuong hoac hoi mau' },
    conditional_combo_effect: { nameVi: 'Hieu ung to hop dieu kien' },
    special_rule_constraint: { nameVi: 'Rang buoc luat chien dau dac thu' },
    require_target_item: { nameVi: 'Bat buoc muc tieu dang cam vat pham' },
    require_shared_type_with_target: { nameVi: 'Bat buoc muc tieu cung he voi nguoi dung' },
    require_all_other_moves_used: { nameVi: 'Bat buoc da dung cac chieu khac' },
    require_condition: { nameEn: 'Require Condition', nameVi: 'Bat buoc dung dieu kien' },
    require_recharge: { nameEn: 'Require Recharge', nameVi: 'Buoc hoi suc' },
    require_terrain: { nameVi: 'Bat buoc co dia hinh' },
    set_entry_hazard: { nameVi: 'Dat bay doi Pokemon tren san' },
    clear_entry_hazards: { nameVi: 'Xoa bay doi Pokemon tren san' },
    set_crit_block: { nameVi: 'Chan sat thuong chi mang' },
    set_move_type_from_context: { nameVi: 'Dat he chieu theo ngu canh' },
    set_move_variant: { nameVi: 'Danh dau bien the chieu dac biet' },
    set_sound_move_block: { nameVi: 'Chan chieu am thanh' },
    set_repeat_move_block: { nameVi: 'Chan lap lai cung chieu' },
    set_target_ability: { nameVi: 'Dat Ability cua muc tieu' },
    set_target_priority_last: { nameVi: 'Day muc tieu xuong cuoi luot' },
    set_turn_order_inversion: { nameVi: 'Dao nguoc thu tu hanh dong' },
    set_drowsy: { nameVi: 'Gay buon ngu roi ngu o luot sau' },
    set_damage_to_user_current_hp: { nameVi: 'Sat thuong bang HP hien tai cua nguoi dung' },
    set_heal_block: { nameVi: 'Chan hoi mau' },
    set_next_attack_always_crit: { nameVi: 'Cu danh tiep theo dam bao chi mang' },
    set_next_attack_never_miss: { nameVi: 'Cu danh tiep theo khong truot' },
    set_normal_moves_become_electric: { nameVi: 'Bien chieu Normal thanh Electric' },
    set_stat_drop_shield: { nameVi: 'Chan giam bac chi so' },
    set_status_move_block: { nameVi: 'Chan dung chieu trang thai' },
    set_status_shield: { nameVi: 'Chan gay trang thai' },
    set_terrain: { nameVi: 'Tao dia hinh' },
    set_weather: { nameVi: 'Tao thoi tiet' },
    set_escape_lock: { nameVi: 'Chan rut lui doi muc tieu' },
    self_faint: { nameVi: 'Nguoi dung tu xiu' },
    self_switch_after_attack: { nameVi: 'Nguoi dung doi Pokemon sau khi tan cong' },
    stat_stage: { nameEn: 'Change Stat Stage', nameVi: 'Tang/giam bac chi so' },
    stat_stage_if: { nameVi: 'Tang/giam bac chi so theo dieu kien' },
    stat_stage_random: { nameVi: 'Tang ngau nhien mot chi so' },
    stat_stage_set: { nameVi: 'Dat truc tiep bac chi so' },
    remove_target_item: { nameVi: 'Loai bo vat pham muc tieu' },
    steal_target_item: { nameVi: 'Cuop vat pham cua muc tieu' },
    swap_held_items: { nameVi: 'Hoan doi vat pham dang cam' },
    restore_consumed_item: { nameVi: 'Khoi phuc vat pham da dung' },
    steal_target_stat_boosts: { nameVi: 'Cuop cac bac chi so duong cua muc tieu' },
    swap_attack_spatk_stages_with_target: { nameVi: 'Hoan doi bac Tan cong va Tan cong dac biet voi muc tieu' },
    swap_all_stat_stages_with_target: { nameVi: 'Hoan doi toan bo bac chi so voi muc tieu' },
    swap_def_spdef_stages_with_target: { nameVi: 'Hoan doi bac Phong thu va Phong thu dac biet voi muc tieu' },
    swap_speed_stages_with_target: { nameVi: 'Hoan doi bac Toc do voi muc tieu' },
    swap_user_attack_defense_stages: { nameVi: 'Hoan doi bac Tan cong va Phong thu cua nguoi dung' },
    transfer_status_to_target: { nameVi: 'Chuyen trang thai cua nguoi dung sang muc tieu' },
    type_filtered_residual_damage: { nameVi: 'Sat thuong cuoi luot theo bo loc he' },
    power_by_fainted_allies: { nameVi: 'Tang suc manh theo so dong doi da guc' },
    power_if_ally_used_move: { nameVi: 'Tang suc manh neu dong doi vua dung chieu' },
    ally_command_move: { nameVi: 'Ra lenh cho dong doi dung chieu' },
    ally_support_effect: { nameVi: 'Hieu ung ho tro dong doi' },
    ally_condition_stat_boost: { nameVi: 'Tang chi so theo dieu kien dong doi' },
    ally_target_dual_mode: { nameVi: 'Che do tan cong hoac hoi cho dong doi' },
    redirect_attacks_to_user: { nameVi: 'Huong don tan cong vao nguoi dung' },
    advanced_battle_rule: { nameVi: 'Ap dung luat chien dau nang cao' },
    copy_target_ability: { nameVi: 'Sao chep Ability cua muc tieu' },
    swap_abilities: { nameVi: 'Hoan doi Ability hai ben' },
    copy_last_move_effect: { nameVi: 'Sao chep hieu ung chieu cuoi cung' },
    post_battle_reward_bonus: { nameVi: 'Thuong them sau tran dau' },
    revive_party_member: { nameVi: 'Hoi sinh dong doi trong doi' },
    flying_ground_interaction: { nameVi: 'Tuong tac he Bay va Dat dac thu' },
    use_move_by_location: { nameVi: 'Chon hieu ung chieu theo vi tri' },
    use_move_by_terrain: { nameVi: 'Chon chieu theo dia hinh' },
    use_defense_as_attack: { nameVi: 'Dung Phong thu thay cho Tan cong' },
    use_higher_offense_stat: { nameVi: 'Dung chi so tan cong cao hon' },
    use_target_attack_as_attack: { nameVi: 'Dung chi so Tan cong cua muc tieu' },
    flavor_only: { nameEn: 'Flavor Only', nameVi: 'Chi mo ta (chua mo phong)' },
    no_op: { nameEn: 'No Operation', nameVi: 'Khong co xu ly' },
    no_battle_effect: { nameVi: 'Khong co hieu ung chien dau' },
    multi_target_damage: { nameVi: 'Sat thuong da muc tieu' },
    reduce_target_pp: { nameVi: 'Giam PP cua muc tieu' },
    override_ghost_immunity: { nameVi: 'Bo qua mien nhiem ma he Thuong/Giac dau' },
    remove_user_type: { nameVi: 'Loai bo mot he cua nguoi dung' },
    power_by_friendship: { nameVi: 'Tang suc manh theo do than thiet' },
    suppress_held_items_field: { nameVi: 'Vo hieu vat pham tren san dau' },
    set_ground_immunity: { nameVi: 'Mien nhiem sat thuong he Dat tam thoi' },
    random_move_execution: { nameVi: 'Thi trien ngau nhien mot chieu' },
    transform_into_target: { nameVi: 'Bien hinh theo muc tieu' },
    weaken_move_type_power: { nameVi: 'Lam yeu sat thuong mot he chieu' },
    set_user_type_from_target: { nameVi: 'Bien he nguoi dung theo muc tieu' },
    set_target_type: { nameVi: 'Dat he cua muc tieu' },
    unsupported_rule: { nameVi: 'Quy tac chua duoc mo phong day du' },
}

const REASON_META_OVERRIDES = {
    z_move_flavor: { nameEn: 'Z-Move Flavor Text', nameVi: 'Mo ta Z-Move' },
    gmax_move_flavor: { nameEn: 'G-Max Flavor Text', nameVi: 'Mo ta G-Max' },
    dynamax_move_flavor: { nameEn: 'Dynamax Flavor Text', nameVi: 'Mo ta Dynamax' },
    explicit_no_battle_effect: { nameEn: 'No Battle Effect', nameVi: 'Khong co hieu ung chien dau' },
    unmodeled_effect: { nameEn: 'Unmodeled Effect', nameVi: 'Hieu ung chua duoc mo phong' },
}

const splitSnakeCase = (value = '') => String(value || '').trim().toLowerCase().split('_').filter(Boolean)

const toTitleCase = (value = '') => {
    const words = splitSnakeCase(value)
    if (words.length === 0) return ''
    return words
        .map((word) => {
            if (TITLE_WORD_OVERRIDES[word]) return TITLE_WORD_OVERRIDES[word]
            return `${word.slice(0, 1).toUpperCase()}${word.slice(1)}`
        })
        .join(' ')
}

const toVietnameseLikeLabel = (value = '') => {
    const words = splitSnakeCase(value)
    if (words.length === 0) return ''
    return words.map((word) => VI_WORD_OVERRIDES[word] || word).join(' ')
}

export const isImplementedEffectOp = (op = '') => {
    const normalized = String(op || '').trim().toLowerCase()
    if (!normalized) return false
    return normalized !== 'flavor_only'
        && normalized !== 'no_op'
        && normalized !== 'unsupported_rule'
}

export const buildEffectOpMeta = (op = '') => {
    const normalized = String(op || '').trim().toLowerCase()
    if (!normalized) {
        return {
            id: '',
            nameEn: '',
            nameVi: '',
            isImplemented: false,
        }
    }

    const override = OP_META_OVERRIDES[normalized] || {}
    return {
        id: normalized,
        nameEn: override.nameEn || toTitleCase(normalized),
        nameVi: override.nameVi || toVietnameseLikeLabel(normalized),
        isImplemented: isImplementedEffectOp(normalized),
    }
}

export const buildEffectReasonMeta = (reason = '') => {
    const normalized = String(reason || '').trim().toLowerCase() || 'unmodeled_effect'
    const override = REASON_META_OVERRIDES[normalized] || {}
    return {
        id: normalized,
        nameEn: override.nameEn || toTitleCase(normalized),
        nameVi: override.nameVi || toVietnameseLikeLabel(normalized),
    }
}

const DEFAULT_TRIGGER_OPTIONS = ['on_hit', 'after_damage', 'end_turn', 'on_calculate_damage', 'on_select_move', 'before_accuracy_check', 'before_opponent_accuracy_check', 'before_damage_taken', 'on_miss']
const DEFAULT_TARGET_OPTIONS = ['self', 'opponent', 'field']

const EFFECT_TEMPLATE_OVERRIDES = {
    apply_status: { trigger: 'on_hit', target: 'opponent', chance: 1, params: { status: 'burn' } },
    apply_status_random: { trigger: 'on_hit', target: 'opponent', chance: 0.3, params: { statuses: ['burn', 'poison'] } },
    clear_status: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    clear_status_if: { trigger: 'on_hit', target: 'self', chance: 1, params: { condition: 'user_is_burned' } },
    stat_stage: { trigger: 'on_hit', target: 'opponent', chance: 1, params: { stat: 'atk', delta: -1 } },
    stat_stage_if: { trigger: 'on_hit', target: 'self', chance: 1, params: { condition: 'target_was_damaged_last_turn', stat: 'atk', delta: 1 } },
    power_modifier_if: { trigger: 'on_calculate_damage', target: 'self', chance: 1, params: { condition: 'weather_sunny', multiplier: 1.5 } },
    power_modifier_by_user_hp: { trigger: 'on_calculate_damage', target: 'self', chance: 1, params: { mode: 'higher' } },
    multi_hit: { trigger: 'on_hit', target: 'opponent', chance: 1, params: { minHits: 2, maxHits: 5 } },
    apply_bind: { trigger: 'on_hit', target: 'opponent', chance: 1, params: { minTurns: 4, maxTurns: 5, fraction: 0.125 } },
    heal_fraction_damage: { trigger: 'after_damage', target: 'self', chance: 1, params: { fraction: 0.5 } },
    heal_fraction_max_hp: { trigger: 'on_hit', target: 'self', chance: 1, params: { fraction: 0.5 } },
    set_drowsy: { trigger: 'on_hit', target: 'opponent', chance: 1, params: { turns: 2 } },
    set_weather: { trigger: 'on_hit', target: 'field', chance: 1, params: { weather: 'rain', turns: 5 } },
    set_terrain: { trigger: 'on_hit', target: 'field', chance: 1, params: { terrain: 'electric', turns: 5 } },
    set_escape_lock: { trigger: 'on_hit', target: 'opponent', chance: 1, params: { turns: 4 } },
    multi_target_damage: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    delayed_damage: { trigger: 'on_hit', target: 'self', chance: 1, params: { turns: 2 } },
    direct_damage_only: { trigger: 'on_hit', target: 'opponent', chance: 1, params: {} },
    reduce_target_pp: { trigger: 'on_hit', target: 'opponent', chance: 1, params: { amount: 3 } },
    override_ghost_immunity: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    remove_user_type: { trigger: 'on_hit', target: 'self', chance: 1, params: { type: 'fire' } },
    add_type_to_target: { trigger: 'on_hit', target: 'opponent', chance: 1, params: { type: 'grass' } },
    no_battle_effect: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    power_by_friendship: { trigger: 'on_calculate_damage', target: 'self', chance: 1, params: {} },
    suppress_held_items_field: { trigger: 'on_hit', target: 'self', chance: 1, params: { turns: 5 } },
    set_ground_immunity: { trigger: 'on_hit', target: 'self', chance: 1, params: { turns: 5 } },
    random_move_execution: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    transform_into_target: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    weaken_move_type_power: { trigger: 'on_hit', target: 'self', chance: 1, params: { type: 'fire', multiplier: 0.67 } },
    average_hp_with_target: { trigger: 'on_hit', target: 'opponent', chance: 1, params: {} },
    fixed_damage_random_user_level: { trigger: 'on_hit', target: 'opponent', chance: 1, params: { minMultiplier: 0.5, maxMultiplier: 1.5 } },
    set_user_type_from_target: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    set_target_type: { trigger: 'on_hit', target: 'opponent', chance: 1, params: { type: 'water' } },
    unsupported_rule: { trigger: 'on_hit', target: 'self', chance: 1, params: { reason: 'unmodeled_effect' } },
    set_move_variant: { trigger: 'on_select_move', target: 'self', chance: 1, params: { variant: 'z_move' } },
    force_switch_target: { trigger: 'on_hit', target: 'opponent', chance: 1, params: {} },
    self_switch_after_attack: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    set_entry_hazard: { trigger: 'on_hit', target: 'opponent', chance: 1, params: { hazard: 'chip_damage' } },
    clear_entry_hazards: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    type_filtered_residual_damage: { trigger: 'end_turn', target: 'opponent', chance: 1, params: { excludedType: 'water', turns: 4, fraction: 1 / 6 } },
    require_recharge: { trigger: 'on_hit', target: 'self', chance: 1, params: { turns: 1 } },
    require_target_item: { trigger: 'on_select_move', target: 'self', chance: 1, params: {} },
    require_shared_type_with_target: { trigger: 'on_select_move', target: 'self', chance: 1, params: {} },
    require_all_other_moves_used: { trigger: 'on_select_move', target: 'self', chance: 1, params: {} },
    conditional_combo_effect: { trigger: 'on_hit', target: 'self', chance: 1, params: { mode: 'pledge_combo' } },
    special_rule_constraint: { trigger: 'on_hit', target: 'self', chance: 1, params: { mode: 'double_battle_or_item_or_lock' } },
    damage_reduction_shield: { trigger: 'on_hit', target: 'self', chance: 1, params: { scope: 'all', multiplier: 0, turns: 1 } },
    set_status_move_block: { trigger: 'on_hit', target: 'opponent', chance: 1, params: { turns: 3 } },
    set_sound_move_block: { trigger: 'on_hit', target: 'opponent', chance: 1, params: { turns: 2 } },
    set_repeat_move_block: { trigger: 'on_hit', target: 'opponent', chance: 1, params: { turns: 2 } },
    copy_target_stat_stages: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    steal_target_stat_boosts: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    force_berry_consumption: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    set_target_priority_last: { trigger: 'on_select_move', target: 'opponent', chance: 1, params: { delta: -7 } },
    set_turn_order_inversion: { trigger: 'on_hit', target: 'self', chance: 1, params: { turns: 5 } },
    random_heal_or_damage: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    power_by_fainted_allies: { trigger: 'on_calculate_damage', target: 'self', chance: 1, params: {} },
    power_if_ally_used_move: { trigger: 'on_calculate_damage', target: 'self', chance: 1, params: { multiplier: 2 } },
    ally_command_move: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    ally_support_effect: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    ally_condition_stat_boost: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    ally_target_dual_mode: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    redirect_attacks_to_user: { trigger: 'on_hit', target: 'self', chance: 1, params: { turns: 1 } },
    advanced_battle_rule: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    copy_target_ability: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    swap_abilities: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    copy_last_move_effect: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    post_battle_reward_bonus: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    revive_party_member: { trigger: 'on_hit', target: 'self', chance: 1, params: { fraction: 0.5 } },
    force_escape_wild: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    flying_ground_interaction: { trigger: 'on_hit', target: 'opponent', chance: 1, params: {} },
    use_move_by_terrain: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    use_move_by_location: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    set_target_ability: { trigger: 'on_hit', target: 'opponent', chance: 1, params: { ability: 'simple' } },
    set_move_type_from_context: { trigger: 'on_calculate_damage', target: 'self', chance: 1, params: { mode: 'memory_item' } },
    ignore_target_ability: { trigger: 'on_calculate_damage', target: 'self', chance: 1, params: { mode: 'ignore' } },
    remove_target_item: { trigger: 'on_hit', target: 'opponent', chance: 1, params: { mode: 'remove' } },
    steal_target_item: { trigger: 'on_hit', target: 'opponent', chance: 1, params: {} },
    swap_held_items: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
    restore_consumed_item: { trigger: 'on_hit', target: 'self', chance: 1, params: {} },
}

export const getDefaultEffectSpecForOp = (op = '') => {
    const normalized = String(op || '').trim().toLowerCase()
    const template = EFFECT_TEMPLATE_OVERRIDES[normalized] || {}
    return {
        op: normalized,
        trigger: template.trigger || 'on_hit',
        target: template.target || 'opponent',
        chance: Number.isFinite(Number(template.chance)) ? Number(template.chance) : 1,
        params: template.params && typeof template.params === 'object' ? template.params : {},
    }
}

export const getEffectTriggerOptions = () => [...DEFAULT_TRIGGER_OPTIONS]
export const getEffectTargetOptions = () => [...DEFAULT_TARGET_OPTIONS]
