import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { battleTrainerApi, itemApi, pokemonApi } from '../../services/adminApi'
import { gameApi } from '../../services/gameApi'
import ImageUpload from '../../components/ImageUpload'

const emptyTrainer = {
    name: '',
    imageUrl: '',
    quote: '',
    isActive: true,
    orderIndex: 0,
    team: [],
    prizePokemonId: '',
    prizePokemonFormId: 'normal',
    prizePokemonLevel: 0,
    prizeItemId: '',
    prizeItemQuantity: 1,
    platinumCoinsReward: 0,
    expReward: 0,
    moonPointsReward: 0,
}

const PRIZE_POKEMON_MODAL_PAGE_SIZE = 40
const PRIZE_POKEMON_FORM_PAGE_SIZE = 18
const TRAINER_PAGE_SIZE = 20

export default function BattleTrainerPage() {
    const [trainers, setTrainers] = useState([])
    const [pokemon, setPokemon] = useState([])
    const [items, setItems] = useState([])
    const [loading, setLoading] = useState(true)
    const [error, setError] = useState('')
    const [form, setForm] = useState({ ...emptyTrainer })
    const [editingId, setEditingId] = useState('')
    const [showPrizePokemonModal, setShowPrizePokemonModal] = useState(false)
    const [prizePokemonSearchTerm, setPrizePokemonSearchTerm] = useState('')
    const [prizePokemonOptions, setPrizePokemonOptions] = useState([])
    const [prizePokemonLookup, setPrizePokemonLookup] = useState({})
    const [prizePokemonPage, setPrizePokemonPage] = useState(1)
    const [prizePokemonFormPage, setPrizePokemonFormPage] = useState(1)
    const [prizePokemonTotalPages, setPrizePokemonTotalPages] = useState(1)
    const [prizePokemonTotal, setPrizePokemonTotal] = useState(0)
    const [prizePokemonLoading, setPrizePokemonLoading] = useState(false)
    const [prizePokemonLoadError, setPrizePokemonLoadError] = useState('')
    const [showTeamPokemonModal, setShowTeamPokemonModal] = useState(false)
    const [teamPokemonTargetIndex, setTeamPokemonTargetIndex] = useState(-1)
    const [teamPokemonSearchTerm, setTeamPokemonSearchTerm] = useState('')
    const [teamPokemonOptions, setTeamPokemonOptions] = useState([])
    const [teamPokemonLookup, setTeamPokemonLookup] = useState({})
    const [teamPokemonPage, setTeamPokemonPage] = useState(1)
    const [teamPokemonFormPage, setTeamPokemonFormPage] = useState(1)
    const [teamPokemonTotalPages, setTeamPokemonTotalPages] = useState(1)
    const [teamPokemonTotal, setTeamPokemonTotal] = useState(0)
    const [teamPokemonLoading, setTeamPokemonLoading] = useState(false)
    const [teamPokemonLoadError, setTeamPokemonLoadError] = useState('')
    const [autoLevelStart, setAutoLevelStart] = useState(1)
    const [autoLevelMax, setAutoLevelMax] = useState(100)
    const [autoLevelStep, setAutoLevelStep] = useState(10)
    const [autoCoinsReward, setAutoCoinsReward] = useState('')
    const [autoExpReward, setAutoExpReward] = useState('')
    const [autoTrainerImageUrl, setAutoTrainerImageUrl] = useState('')
    const [autoTrainerImageUrls, setAutoTrainerImageUrls] = useState([])
    const [autoGenerating, setAutoGenerating] = useState(false)
    const [deletingAll, setDeletingAll] = useState(false)
    const [deletingAutoGenerated, setDeletingAutoGenerated] = useState(false)
    const [showCreateTrainerForm, setShowCreateTrainerForm] = useState(false)
    const [trainerPagination, setTrainerPagination] = useState({
        page: 1,
        pages: 1,
        total: 0,
        limit: TRAINER_PAGE_SIZE,
    })
    const [autoGeneratedTrainerCount, setAutoGeneratedTrainerCount] = useState(0)

    useEffect(() => {
        loadReferenceData()
    }, [])

    useEffect(() => {
        loadTrainers(trainerPagination.page)
    }, [trainerPagination.page])

    useEffect(() => {
        if (!showPrizePokemonModal) return
        loadPrizePokemonOptions()
    }, [showPrizePokemonModal, prizePokemonPage, prizePokemonSearchTerm])

    useEffect(() => {
        if (!showTeamPokemonModal) return
        loadTeamPokemonOptions()
    }, [showTeamPokemonModal, teamPokemonPage, teamPokemonSearchTerm])

    const loadReferenceData = async () => {
        try {
            const [pokemonData, itemData] = await Promise.all([
                gameApi.getPokemonList({ page: 1, limit: 5000 }),
                itemApi.list({ page: 1, limit: 5000 }),
            ])
            setPokemon(pokemonData.pokemon || [])
            setItems(itemData.items || [])
        } catch (err) {
            setError(err.message)
        }
    }

    const loadTrainers = async (targetPage = trainerPagination.page) => {
        try {
            setLoading(true)
            setError('')
            const data = await battleTrainerApi.list({
                page: targetPage,
                limit: trainerPagination.limit,
            })

            const rows = Array.isArray(data?.trainers) ? data.trainers : []
            const total = Math.max(0, Number(data?.pagination?.total) || 0)
            const totalPages = Math.max(1, Number(data?.pagination?.pages) || 1)
            const limit = Math.max(1, Number(data?.pagination?.limit) || TRAINER_PAGE_SIZE)

            if (rows.length === 0 && total > 0 && targetPage > 1) {
                setTrainerPagination((prev) => ({
                    ...prev,
                    page: Math.max(1, totalPages),
                }))
                return
            }

            setTrainers(rows)
            setTrainerPagination((prev) => ({
                ...prev,
                page: Math.max(1, Number(data?.pagination?.page) || targetPage),
                pages: totalPages,
                total,
                limit,
            }))
            setAutoGeneratedTrainerCount(Math.max(0, Number(data?.summary?.autoGeneratedTotal) || 0))
        } catch (err) {
            setError(err.message || 'Không thể tải danh sách trainer')
            setTrainers([])
            setTrainerPagination((prev) => ({
                ...prev,
                pages: 1,
                total: 0,
            }))
            setAutoGeneratedTrainerCount(0)
        } finally {
            setLoading(false)
        }
    }

    const loadPrizePokemonOptions = async () => {
        try {
            setPrizePokemonLoading(true)
            setPrizePokemonLoadError('')

            const normalizedSearch = String(prizePokemonSearchTerm || '').trim()
            const data = await pokemonApi.list({
                page: prizePokemonPage,
                limit: PRIZE_POKEMON_MODAL_PAGE_SIZE,
                ...(normalizedSearch ? { search: normalizedSearch } : {}),
            })

            const rows = Array.isArray(data?.pokemon) ? data.pokemon : []
            setPrizePokemonOptions(rows)
            setPrizePokemonTotalPages(Math.max(1, Number(data?.pagination?.pages) || 1))
            setPrizePokemonTotal(Math.max(0, Number(data?.pagination?.total) || 0))
            setPrizePokemonLookup((prev) => {
                const next = { ...prev }
                rows.forEach((entry) => {
                    if (entry?._id) next[entry._id] = entry
                })
                return next
            })
        } catch (err) {
            setPrizePokemonOptions([])
            setPrizePokemonTotalPages(1)
            setPrizePokemonTotal(0)
            setPrizePokemonLoadError(err.message || 'Không thể tải danh sách Pokemon')
        } finally {
            setPrizePokemonLoading(false)
        }
    }

    const loadTeamPokemonOptions = async () => {
        try {
            setTeamPokemonLoading(true)
            setTeamPokemonLoadError('')

            const normalizedSearch = String(teamPokemonSearchTerm || '').trim()
            const data = await pokemonApi.list({
                page: teamPokemonPage,
                limit: PRIZE_POKEMON_MODAL_PAGE_SIZE,
                ...(normalizedSearch ? { search: normalizedSearch } : {}),
            })

            const rows = Array.isArray(data?.pokemon) ? data.pokemon : []
            setTeamPokemonOptions(rows)
            setTeamPokemonTotalPages(Math.max(1, Number(data?.pagination?.pages) || 1))
            setTeamPokemonTotal(Math.max(0, Number(data?.pagination?.total) || 0))
            setTeamPokemonLookup((prev) => {
                const next = { ...prev }
                rows.forEach((entry) => {
                    if (entry?._id) next[entry._id] = entry
                })
                return next
            })
        } catch (err) {
            setTeamPokemonOptions([])
            setTeamPokemonTotalPages(1)
            setTeamPokemonTotal(0)
            setTeamPokemonLoadError(err.message || 'Không thể tải danh sách Pokemon đội hình')
        } finally {
            setTeamPokemonLoading(false)
        }
    }

    const resetForm = () => {
        setForm({ ...emptyTrainer })
        setEditingId('')
        setShowTeamPokemonModal(false)
        setTeamPokemonTargetIndex(-1)
    }

    const handleAddTeam = () => {
        setForm((prev) => ({
            ...prev,
            team: [...prev.team, { pokemonId: '', level: 5, formId: 'normal' }],
        }))
    }

    const handleOpenTeamPokemonModal = (targetIndex) => {
        if (!Number.isInteger(targetIndex) || targetIndex < 0) return
        const currentTeamEntry = form.team?.[targetIndex] || null
        const currentPokemon = pokemon.find((entry) => entry._id === currentTeamEntry?.pokemonId)
            || teamPokemonLookup[currentTeamEntry?.pokemonId]
            || null
        const suggestedSearch = currentPokemon?.name
            || (currentPokemon?.pokedexNumber ? String(currentPokemon.pokedexNumber) : '')

        setTeamPokemonTargetIndex(targetIndex)
        setTeamPokemonSearchTerm(suggestedSearch)
        setTeamPokemonPage(1)
        setTeamPokemonFormPage(1)
        setTeamPokemonLoadError('')
        setShowTeamPokemonModal(true)
    }

    const buildRandomTeam = () => {
        if (!pokemon.length) return []
        const picked = []
        const used = new Set()
        while (picked.length < Math.min(3, pokemon.length)) {
            const index = Math.floor(Math.random() * pokemon.length)
            if (used.has(index)) continue
            used.add(index)
            picked.push({
                pokemonId: pokemon[index]._id,
                level: Math.floor(Math.random() * 8) + 3,
                formId: 'normal',
            })
        }
        return picked
    }

    const handleUpdateTeam = (index, key, value) => {
        setForm((prev) => {
            const team = [...prev.team]
            team[index] = { ...team[index], [key]: value }
            return { ...prev, team }
        })
    }

    const handleRemoveTeam = (index) => {
        setForm((prev) => {
            const team = prev.team.filter((_, i) => i !== index)
            return { ...prev, team }
        })
        if (showTeamPokemonModal) {
            setShowTeamPokemonModal(false)
            setTeamPokemonTargetIndex(-1)
        }
    }

    const handleClearTeamPokemon = (index) => {
        if (!Number.isInteger(index) || index < 0) return
        setForm((prev) => {
            if (!prev.team[index]) return prev
            const team = [...prev.team]
            team[index] = { ...team[index], pokemonId: '', formId: 'normal' }
            return { ...prev, team }
        })
    }

    const handleSelectTeamPokemon = (pokemonId, formId = 'normal') => {
        const targetIndex = Number(teamPokemonTargetIndex)
        if (!Number.isInteger(targetIndex) || targetIndex < 0) return

        setForm((prev) => {
            if (!prev.team[targetIndex]) return prev
            const team = [...prev.team]
            team[targetIndex] = {
                ...team[targetIndex],
                pokemonId,
                formId: String(formId || '').trim().toLowerCase() || 'normal',
            }
            return { ...prev, team }
        })

        setShowTeamPokemonModal(false)
        setTeamPokemonTargetIndex(-1)
    }

    const handleSubmit = async (e) => {
        e.preventDefault()
        setError('')
        try {
            const payload = {
                ...form,
                team: form.team.length ? form.team : buildRandomTeam(),
                prizePokemonId: form.prizePokemonId || null,
                prizePokemonFormId: form.prizePokemonId
                    ? (String(form.prizePokemonFormId || '').trim().toLowerCase() || 'normal')
                    : null,
                prizePokemonLevel: form.prizePokemonId
                    ? Math.max(0, Number.parseInt(form.prizePokemonLevel, 10) || 0)
                    : 0,
                prizeItemId: form.prizeItemId || null,
                prizeItemQuantity: form.prizeItemId
                    ? Math.max(1, Number.parseInt(form.prizeItemQuantity, 10) || 1)
                    : 1,
                moonPointsReward: Math.max(0, Number.parseInt(form.moonPointsReward, 10) || 0),
            }
            if (editingId) {
                await battleTrainerApi.update(editingId, payload)
            } else {
                await battleTrainerApi.create(payload)
            }
            resetForm()
            await loadTrainers(trainerPagination.page)
        } catch (err) {
            setError(err.message)
        }
    }

    const handleEdit = (trainer) => {
        setShowCreateTrainerForm(false)
        setEditingId(trainer._id)
        setForm({
            name: trainer.name || '',
            imageUrl: trainer.imageUrl || '',
            quote: trainer.quote || '',
            isActive: trainer.isActive !== undefined ? trainer.isActive : true,
            orderIndex: trainer.orderIndex || 0,
            team: (trainer.team || []).map((entry) => ({
                pokemonId: entry.pokemonId?._id || entry.pokemonId || '',
                level: entry.level || 5,
                formId: entry.formId || 'normal',
            })),
            prizePokemonId: trainer.prizePokemonId?._id || trainer.prizePokemonId || '',
            prizePokemonFormId: String(trainer.prizePokemonFormId || trainer.prizePokemonId?.defaultFormId || 'normal').trim().toLowerCase() || 'normal',
            prizePokemonLevel: Math.max(0, Number(trainer.prizePokemonLevel) || 0),
            prizeItemId: trainer.prizeItemId?._id || trainer.prizeItemId || '',
            prizeItemQuantity: Math.max(1, Number(trainer.prizeItemQuantity) || 1),
            platinumCoinsReward: trainer.platinumCoinsReward || 0,
            expReward: trainer.expReward || 0,
            moonPointsReward: trainer.moonPointsReward || 0,
        })
    }

    const handleDelete = async (id) => {
        if (!confirm('Xóa trainer này?')) return
        await battleTrainerApi.delete(id)
        await loadTrainers(trainerPagination.page)
    }

    const handleDeleteAll = async () => {
        if (!trainers.length) return
        if (!confirm('Xóa toàn bộ trainer battle hiện có? Hành động này không thể hoàn tác.')) return
        try {
            setError('')
            setDeletingAll(true)
            await battleTrainerApi.deleteAll()
            resetForm()
            setTrainerPagination((prev) => ({ ...prev, page: 1 }))
            await loadTrainers(1)
        } catch (err) {
            setError(err.message || 'Xóa toàn bộ trainer thất bại')
        } finally {
            setDeletingAll(false)
        }
    }

    const handleDeleteAutoGenerated = async () => {
        const autoGeneratedCount = trainers.filter((entry) => entry?.autoGenerated).length
        if (autoGeneratedCount === 0) return
        if (!confirm(`Xóa ${autoGeneratedCount} trainer auto-generated? Trainer tạo tay sẽ được giữ lại.`)) return
        try {
            setError('')
            setDeletingAutoGenerated(true)
            await battleTrainerApi.deleteAutoGenerated()
            resetForm()
            setTrainerPagination((prev) => ({ ...prev, page: 1 }))
            await loadTrainers(1)
        } catch (err) {
            setError(err.message || 'Xóa trainer auto-generated thất bại')
        } finally {
            setDeletingAutoGenerated(false)
        }
    }

    const handleAutoGenerateByMilestone = async () => {
        try {
            setError('')
            setAutoGenerating(true)
            const payload = {
                startLevel: autoLevelStart,
                maxLevel: autoLevelMax,
                step: autoLevelStep,
                teamSize: 3,
                imageUrl: autoTrainerImageUrl,
                imageUrls: autoTrainerImageUrls,
            }

            const normalizedCoinsReward = String(autoCoinsReward || '').trim()
            const normalizedExpReward = String(autoExpReward || '').trim()

            if (normalizedCoinsReward !== '') {
                payload.platinumCoinsReward = Math.max(0, Number.parseInt(normalizedCoinsReward, 10) || 0)
            }
            if (normalizedExpReward !== '') {
                payload.expReward = Math.max(0, Number.parseInt(normalizedExpReward, 10) || 0)
            }

            await battleTrainerApi.autoGenerate(payload)
            setTrainerPagination((prev) => ({ ...prev, page: 1 }))
            await loadTrainers(1)
        } catch (err) {
            setError(err.message)
        } finally {
            setAutoGenerating(false)
        }
    }

    const handleOpenPrizePokemonModal = () => {
        setPrizePokemonSearchTerm('')
        setPrizePokemonPage(1)
        setPrizePokemonFormPage(1)
        setPrizePokemonLoadError('')
        setShowPrizePokemonModal(true)
    }

    const handleSelectPrizePokemon = (pokemonId, formId = 'normal') => {
        setForm((prev) => ({
            ...prev,
            prizePokemonId: pokemonId,
            prizePokemonFormId: String(formId || '').trim().toLowerCase() || 'normal',
        }))
        setShowPrizePokemonModal(false)
    }

    const handleClearPrizePokemon = () => {
        setForm((prev) => ({
            ...prev,
            prizePokemonId: '',
            prizePokemonFormId: 'normal',
            prizePokemonLevel: 0,
        }))
    }

    const getPokemonImageUrl = (entry) => {
        const pokedexNumber = Number(entry?.pokedexNumber)
        return entry?.imageUrl
            || entry?.sprites?.normal
            || entry?.sprites?.front_default
            || (Number.isFinite(pokedexNumber)
                ? `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${pokedexNumber}.png`
                : 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png')
    }

    const normalizePokemonFormId = (value) => String(value || '').trim().toLowerCase() || 'normal'

    const getPokemonFormsForDisplay = (entry) => {
        const defaultFormId = normalizePokemonFormId(entry?.defaultFormId)
        const rawForms = Array.isArray(entry?.forms) ? entry.forms : []

        const normalizedForms = rawForms
            .map((form) => {
                const formId = normalizePokemonFormId(form?.formId || defaultFormId)
                return {
                    formId,
                    formName: String(form?.formName || '').trim() || formId,
                    resolvedImageUrl: form?.imageUrl
                        || form?.sprites?.normal
                        || form?.sprites?.icon
                        || getPokemonImageUrl(entry),
                    isDefault: formId === defaultFormId,
                }
            })
            .filter((form, index, arr) => arr.findIndex((item) => item.formId === form.formId) === index)

        if (!normalizedForms.some((form) => form.formId === defaultFormId)) {
            normalizedForms.unshift({
                formId: defaultFormId,
                formName: defaultFormId,
                resolvedImageUrl: getPokemonImageUrl(entry),
                isDefault: true,
            })
        }

        return normalizedForms
            .sort((a, b) => {
                if (a.formId === defaultFormId) return -1
                if (b.formId === defaultFormId) return 1
                return a.formId.localeCompare(b.formId)
            })
    }

    const selectedPrizePokemon = pokemon.find((entry) => entry._id === form.prizePokemonId)
        || prizePokemonLookup[form.prizePokemonId]
        || null
    const selectedPrizeItem = items.find((entry) => entry._id === form.prizeItemId) || null
    const selectedPrizePokemonForms = selectedPrizePokemon ? getPokemonFormsForDisplay(selectedPrizePokemon) : []
    const normalizedPrizePokemonFormId = normalizePokemonFormId(form.prizePokemonFormId)
    const selectedPrizePokemonForm = selectedPrizePokemonForms.find((entry) => entry.formId === normalizedPrizePokemonFormId)
        || selectedPrizePokemonForms[0]
        || null

    const activeTeamEntry = Number.isInteger(Number(teamPokemonTargetIndex))
        ? form.team[Number(teamPokemonTargetIndex)]
        : null
    const selectedTeamPokemon = pokemon.find((entry) => entry._id === activeTeamEntry?.pokemonId)
        || teamPokemonLookup[activeTeamEntry?.pokemonId]
        || null
    const selectedTeamPokemonForms = selectedTeamPokemon ? getPokemonFormsForDisplay(selectedTeamPokemon) : []
    const normalizedTeamPokemonFormId = normalizePokemonFormId(activeTeamEntry?.formId)
    const selectedTeamPokemonForm = selectedTeamPokemonForms.find((entry) => entry.formId === normalizedTeamPokemonFormId)
        || selectedTeamPokemonForms[0]
        || null

    const allPrizePokemonFormRows = prizePokemonOptions.flatMap((entry) => {
        const forms = getPokemonFormsForDisplay(entry)
        return forms.map((rowForm) => ({
            key: `${entry._id}:${rowForm.formId}`,
            pokemon: entry,
            form: rowForm,
        }))
    })

    const prizePokemonFormTotal = allPrizePokemonFormRows.length
    const prizePokemonFormTotalPages = Math.max(1, Math.ceil(prizePokemonFormTotal / PRIZE_POKEMON_FORM_PAGE_SIZE))
    const safePrizePokemonFormPage = Math.min(prizePokemonFormPage, prizePokemonFormTotalPages)
    const prizePokemonFormSliceStart = (safePrizePokemonFormPage - 1) * PRIZE_POKEMON_FORM_PAGE_SIZE
    const prizePokemonFormRows = allPrizePokemonFormRows.slice(
        prizePokemonFormSliceStart,
        prizePokemonFormSliceStart + PRIZE_POKEMON_FORM_PAGE_SIZE
    )

    const allTeamPokemonFormRows = teamPokemonOptions.flatMap((entry) => {
        const forms = getPokemonFormsForDisplay(entry)
        return forms.map((rowForm) => ({
            key: `${entry._id}:${rowForm.formId}`,
            pokemon: entry,
            form: rowForm,
        }))
    })

    const teamPokemonFormTotal = allTeamPokemonFormRows.length
    const teamPokemonFormTotalPages = Math.max(1, Math.ceil(teamPokemonFormTotal / PRIZE_POKEMON_FORM_PAGE_SIZE))
    const safeTeamPokemonFormPage = Math.min(teamPokemonFormPage, teamPokemonFormTotalPages)
    const teamPokemonFormSliceStart = (safeTeamPokemonFormPage - 1) * PRIZE_POKEMON_FORM_PAGE_SIZE
    const teamPokemonFormRows = allTeamPokemonFormRows.slice(
        teamPokemonFormSliceStart,
        teamPokemonFormSliceStart + PRIZE_POKEMON_FORM_PAGE_SIZE
    )

    const prizePokemonPageStart = prizePokemonTotal > 0
        ? ((prizePokemonPage - 1) * PRIZE_POKEMON_MODAL_PAGE_SIZE) + 1
        : 0
    const prizePokemonPageEnd = prizePokemonTotal > 0
        ? Math.min(prizePokemonTotal, prizePokemonPage * PRIZE_POKEMON_MODAL_PAGE_SIZE)
        : 0
    const prizePokemonFormPageStart = prizePokemonFormTotal > 0
        ? prizePokemonFormSliceStart + 1
        : 0
    const prizePokemonFormPageEnd = prizePokemonFormTotal > 0
        ? Math.min(prizePokemonFormTotal, prizePokemonFormSliceStart + PRIZE_POKEMON_FORM_PAGE_SIZE)
        : 0
    const teamPokemonPageStart = teamPokemonTotal > 0
        ? ((teamPokemonPage - 1) * PRIZE_POKEMON_MODAL_PAGE_SIZE) + 1
        : 0
    const teamPokemonPageEnd = teamPokemonTotal > 0
        ? Math.min(teamPokemonTotal, teamPokemonPage * PRIZE_POKEMON_MODAL_PAGE_SIZE)
        : 0
    const teamPokemonFormPageStart = teamPokemonFormTotal > 0
        ? teamPokemonFormSliceStart + 1
        : 0
    const teamPokemonFormPageEnd = teamPokemonFormTotal > 0
        ? Math.min(teamPokemonFormTotal, teamPokemonFormSliceStart + PRIZE_POKEMON_FORM_PAGE_SIZE)
        : 0
    const trainerPageStart = trainerPagination.total > 0
        ? ((trainerPagination.page - 1) * trainerPagination.limit) + 1
        : 0
    const trainerPageEnd = trainerPagination.total > 0
        ? Math.min(trainerPagination.total, trainerPagination.page * trainerPagination.limit)
        : 0
    const trainerPageItems = useMemo(() => {
        const totalPages = Math.max(1, Number(trainerPagination.pages) || 1)
        const currentPage = Math.max(1, Number(trainerPagination.page) || 1)

        if (totalPages <= 9) {
            return Array.from({ length: totalPages }, (_, index) => index + 1)
        }

        const pages = [1]
        const start = Math.max(2, currentPage - 2)
        const end = Math.min(totalPages - 1, currentPage + 2)

        if (start > 2) pages.push('...')
        for (let value = start; value <= end; value += 1) {
            pages.push(value)
        }
        if (end < totalPages - 1) pages.push('...')
        pages.push(totalPages)

        return pages
    }, [trainerPagination.page, trainerPagination.pages])

    useEffect(() => {
        setPrizePokemonFormPage((prev) => {
            const normalized = Math.max(1, Math.min(prev, prizePokemonFormTotalPages))
            return normalized === prev ? prev : normalized
        })
    }, [prizePokemonFormTotalPages])

    useEffect(() => {
        setTeamPokemonFormPage((prev) => {
            const normalized = Math.max(1, Math.min(prev, teamPokemonFormTotalPages))
            return normalized === prev ? prev : normalized
        })
    }, [teamPokemonFormTotalPages])

    const isEditingTrainer = Boolean(editingId)

    return (
        <div className="rounded border border-blue-400 bg-white shadow-sm">
            <div className="border-b border-blue-400 bg-gradient-to-t from-blue-600 to-cyan-500 px-3 py-2">
                <h1 className="text-lg font-bold text-white uppercase tracking-wider">Quản Lý Battle</h1>
            </div>
            <div className="p-4">
                {error && <div className="p-3 mb-4 bg-red-50 text-red-700 border border-red-200 rounded text-sm">{error}</div>}

                <div className="mb-4 border border-emerald-200 rounded p-3 bg-emerald-50/60">
                    <div className="flex flex-col md:flex-row md:items-end gap-3">
                        <div>
                            <label className="block text-slate-700 text-xs font-bold mb-1.5 uppercase">Mốc bắt đầu</label>
                            <input
                                type="number"
                                min="1"
                                value={autoLevelStart}
                                onChange={(e) => setAutoLevelStart(Math.max(1, Number.parseInt(e.target.value, 10) || 1))}
                                className="w-24 px-2 py-1.5 bg-white border border-slate-300 rounded text-sm"
                            />
                        </div>
                        <div>
                            <label className="block text-slate-700 text-xs font-bold mb-1.5 uppercase">Mốc tối đa</label>
                            <input
                                type="number"
                                min="1"
                                value={autoLevelMax}
                                onChange={(e) => setAutoLevelMax(Math.max(1, Number.parseInt(e.target.value, 10) || 1))}
                                className="w-24 px-2 py-1.5 bg-white border border-slate-300 rounded text-sm"
                            />
                        </div>
                        <div>
                            <label className="block text-slate-700 text-xs font-bold mb-1.5 uppercase">Bước cấp</label>
                            <input
                                type="number"
                                min="1"
                                value={autoLevelStep}
                                onChange={(e) => setAutoLevelStep(Math.max(1, Number.parseInt(e.target.value, 10) || 1))}
                                className="w-24 px-2 py-1.5 bg-white border border-slate-300 rounded text-sm"
                            />
                        </div>
                        <button
                            type="button"
                            onClick={handleAutoGenerateByMilestone}
                            disabled={autoGenerating}
                            className="px-3 py-2 bg-emerald-600 hover:bg-emerald-700 disabled:opacity-60 disabled:cursor-not-allowed text-white font-bold rounded text-sm"
                        >
                            {autoGenerating ? 'Đang tạo...' : 'Auto tạo HLV mỗi 10 cấp'}
                        </button>
                    </div>
                    <div className="mt-3 grid grid-cols-1 md:grid-cols-2 gap-3">
                        <div>
                            <ImageUpload
                                currentImage={autoTrainerImageUrl}
                                onUploadSuccess={(url) => {
                                    const nextUrls = Array.isArray(url)
                                        ? url.filter(Boolean)
                                        : [url].filter(Boolean)
                                    setAutoTrainerImageUrls(nextUrls)
                                    setAutoTrainerImageUrl(nextUrls[0] || '')
                                }}
                                multiple
                                label="Ảnh dùng cho trainer auto (chọn nhiều ảnh)"
                            />
                            {autoTrainerImageUrls.length > 0 && (
                                <div className="mt-2 text-[11px] text-emerald-800 font-medium">
                                    Đã chọn {autoTrainerImageUrls.length} ảnh, auto tạo sẽ gán lần lượt theo mốc cấp.
                                </div>
                            )}
                        </div>
                        <div>
                            <label className="block text-slate-700 text-xs font-bold mb-1.5 uppercase">URL ảnh trainer auto</label>
                            <input
                                type="text"
                                value={autoTrainerImageUrl}
                                onChange={(e) => {
                                    const nextUrl = e.target.value
                                    setAutoTrainerImageUrl(nextUrl)
                                    setAutoTrainerImageUrls(nextUrl ? [nextUrl] : [])
                                }}
                                className="w-full px-3 py-2 bg-white border border-slate-300 rounded text-sm"
                                placeholder="Để trống nếu không muốn đổi ảnh trainer auto"
                            />
                        </div>
                    </div>
                    <div className="mt-3 grid grid-cols-1 md:grid-cols-2 gap-3">
                        <div>
                            <label className="block text-slate-700 text-xs font-bold mb-1.5 uppercase">🪙 Xu nhận được</label>
                            <input
                                type="number"
                                min="0"
                                value={autoCoinsReward}
                                onChange={(e) => setAutoCoinsReward(e.target.value)}
                                className="w-full px-3 py-2 bg-white border border-slate-300 rounded text-sm"
                                placeholder="Để trống = Lv x 10"
                            />
                        </div>
                        <div>
                            <label className="block text-slate-700 text-xs font-bold mb-1.5 uppercase">⭐ EXP nhận được</label>
                            <input
                                type="number"
                                min="0"
                                value={autoExpReward}
                                onChange={(e) => setAutoExpReward(e.target.value)}
                                className="w-full px-3 py-2 bg-white border border-slate-300 rounded text-sm"
                                placeholder="Để trống = Lv x 10"
                            />
                        </div>
                    </div>
                    <p className="mt-2 text-[11px] text-emerald-800">
                        Nếu để trống phần thưởng thì hệ thống dùng mặc định: Lv x 10 cho Xu và EXP. Trainer auto không có thưởng Điểm Nguyệt Các. Nếu có ảnh ở trên, trainer auto sẽ dùng ảnh đó.
                    </p>
                </div>
                <div className="mb-4 border border-blue-200 rounded bg-blue-50/50 p-3">
                    <div className="flex items-center justify-between gap-2">
                        <div className="text-sm font-bold text-blue-900 uppercase tracking-wide">Form tạo trainer</div>
                        <button
                            type="button"
                            onClick={() => setShowCreateTrainerForm((prev) => !prev)}
                            className="px-3 py-1.5 text-xs font-bold rounded border border-blue-300 bg-white text-blue-700 hover:bg-blue-50"
                        >
                            {showCreateTrainerForm ? 'Thu gọn' : 'Mở form tạo'}
                        </button>
                    </div>
                    {!showCreateTrainerForm && !isEditingTrainer && (
                        <div className="mt-2 text-xs text-slate-600">
                            Form tạo trainer đang được thu gọn. Bấm "Mở form tạo" để thêm trainer mới.
                        </div>
                    )}
                </div>

                {isEditingTrainer && (
                    <div
                        className="fixed inset-0 bg-slate-900/45 z-30"
                        onClick={resetForm}
                    />
                )}

                {(showCreateTrainerForm || isEditingTrainer) && (
                    <div className={isEditingTrainer ? 'fixed inset-x-0 bottom-0 z-40 px-3 pb-3' : ''}>
                        <div className={isEditingTrainer ? 'mx-auto max-w-5xl bg-white border border-slate-300 rounded-t-xl shadow-2xl max-h-[86vh] overflow-y-auto' : ''}>
                            {isEditingTrainer && (
                                <div className="sticky top-0 z-[200] bg-gradient-to-t from-blue-600 to-cyan-500 text-white px-4 py-2 border-b border-blue-700 flex items-center justify-between">
                                    <div className="font-bold">Đang sửa trainer</div>
                                    <button
                                        type="button"
                                        onClick={resetForm}
                                        className="px-2 py-1 text-xs font-bold rounded bg-white/15 hover:bg-white/25"
                                    >
                                        Đóng
                                    </button>
                                </div>
                            )}

                            <form onSubmit={handleSubmit} className={`space-y-4 border border-slate-200 rounded p-4 bg-slate-50 ${isEditingTrainer ? 'rounded-t-none border-x-0 border-b-0' : ''}`}>
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                    <div>
                                        <label className="block text-slate-700 text-xs font-bold mb-1.5 uppercase">Tên Trainer</label>
                                        <input
                                            type="text"
                                            value={form.name}
                                            onChange={(e) => setForm({ ...form, name: e.target.value })}
                                            className="w-full px-3 py-2 bg-white border border-slate-300 rounded text-sm"
                                        />
                                    </div>
                                    <div>
                                        <label className="block text-slate-700 text-xs font-bold mb-1.5 uppercase">Ảnh Trainer</label>
                                        <ImageUpload
                                            currentImage={form.imageUrl}
                                            onUploadSuccess={(url) => setForm({ ...form, imageUrl: Array.isArray(url) ? (url[0] || '') : (url || '') })}
                                        />
                                        <input
                                            type="text"
                                            value={form.imageUrl}
                                            onChange={(e) => setForm({ ...form, imageUrl: e.target.value })}
                                            className="mt-2 w-full px-3 py-2 bg-white border border-slate-300 rounded text-sm"
                                            placeholder="/assets/08_trainer_female.png"
                                        />
                                    </div>
                                </div>
                                <div>
                                    <label className="block text-slate-700 text-xs font-bold mb-1.5 uppercase">Lời thoại</label>
                                    <input
                                        type="text"
                                        value={form.quote}
                                        onChange={(e) => setForm({ ...form, quote: e.target.value })}
                                        className="w-full px-3 py-2 bg-white border border-slate-300 rounded text-sm"
                                    />
                                </div>
                                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                    <div>
                                        <label className="block text-slate-700 text-xs font-bold mb-1.5 uppercase">Thứ tự</label>
                                        <input
                                            type="number"
                                            min="0"
                                            value={form.orderIndex}
                                            onChange={(e) => setForm({ ...form, orderIndex: parseInt(e.target.value) || 0 })}
                                            className="w-full px-3 py-2 bg-white border border-slate-300 rounded text-sm"
                                        />
                                    </div>
                                    <div>
                                        <label className="block text-slate-700 text-xs font-bold mb-1.5 uppercase">Trạng thái</label>
                                        <select
                                            value={form.isActive ? 'active' : 'inactive'}
                                            onChange={(e) => setForm({ ...form, isActive: e.target.value === 'active' })}
                                            className="w-full px-3 py-2 bg-white border border-slate-300 rounded text-sm"
                                        >
                                            <option value="active">Hoạt động</option>
                                            <option value="inactive">Ẩn</option>
                                        </select>
                                    </div>
                                    <div>
                                        <label className="block text-slate-700 text-xs font-bold mb-1.5 uppercase">Pokémon thưởng</label>
                                        <div className="space-y-2">
                                            <button
                                                type="button"
                                                onClick={handleOpenPrizePokemonModal}
                                                className="w-full px-3 py-2 bg-white border border-slate-300 rounded text-sm text-left hover:border-blue-400 transition-colors"
                                            >
                                                {selectedPrizePokemon
                                                    ? `#${String(selectedPrizePokemon.pokedexNumber || 0).padStart(3, '0')} - ${selectedPrizePokemon.name}${selectedPrizePokemonForm && !selectedPrizePokemonForm.isDefault ? ` (${selectedPrizePokemonForm.formName || selectedPrizePokemonForm.formId})` : ''}`
                                                    : (form.prizePokemonId ? 'Pokemon đã chọn không còn trong danh sách' : 'Chọn Pokemon phần thưởng')}
                                            </button>
                                            {selectedPrizePokemon && (
                                                <div className="flex items-center justify-between gap-2 rounded border border-slate-200 bg-white px-2 py-1.5">
                                                    <div className="flex items-center gap-2 min-w-0">
                                                        <img
                                                            src={selectedPrizePokemonForm?.resolvedImageUrl || getPokemonImageUrl(selectedPrizePokemon)}
                                                            alt={selectedPrizePokemon.name}
                                                            className="w-8 h-8 object-contain pixelated"
                                                        />
                                                        <div className="min-w-0">
                                                            <div className="text-xs font-semibold text-slate-700 truncate">{selectedPrizePokemon.name}</div>
                                                            <div className="text-[11px] text-slate-500 font-mono">#{String(selectedPrizePokemon.pokedexNumber || 0).padStart(3, '0')}</div>
                                                            {selectedPrizePokemonForm && (
                                                                <div className="mt-1">
                                                                    <span className="px-1.5 py-0.5 rounded-[3px] text-[10px] font-bold uppercase tracking-wide bg-blue-100 text-blue-700 border border-blue-200">
                                                                        Dạng: {selectedPrizePokemonForm.formName || selectedPrizePokemonForm.formId}
                                                                    </span>
                                                                </div>
                                                            )}
                                                        </div>
                                                    </div>
                                                    <button
                                                        type="button"
                                                        onClick={handleClearPrizePokemon}
                                                        className="px-2 py-1 text-[11px] font-bold bg-red-50 border border-red-200 text-red-700 rounded"
                                                    >
                                                        Bỏ chọn
                                                    </button>
                                                </div>
                                            )}
                                            <div>
                                                <label className="block text-[11px] font-bold text-slate-600 uppercase mb-1">
                                                    Cấp Pokémon thưởng (0 = auto Lv 5)
                                                </label>
                                                <input
                                                    type="number"
                                                    min="0"
                                                    value={form.prizePokemonLevel}
                                                    onChange={(e) => setForm((prev) => ({
                                                        ...prev,
                                                        prizePokemonLevel: Math.max(0, Number.parseInt(e.target.value, 10) || 0),
                                                    }))}
                                                    disabled={!form.prizePokemonId}
                                                    className="w-full px-3 py-2 bg-white border border-slate-300 rounded text-sm disabled:bg-slate-100 disabled:text-slate-400"
                                                    placeholder="0"
                                                />
                                            </div>
                                        </div>
                                    </div>
                                    <div>
                                        <label className="block text-slate-700 text-xs font-bold mb-1.5 uppercase">Vật phẩm thưởng</label>
                                        <select
                                            value={form.prizeItemId}
                                            onChange={(e) => {
                                                const nextItemId = e.target.value
                                                setForm((prev) => ({
                                                    ...prev,
                                                    prizeItemId: nextItemId,
                                                    prizeItemQuantity: nextItemId ? Math.max(1, Number.parseInt(prev.prizeItemQuantity, 10) || 1) : 1,
                                                }))
                                            }}
                                            className="w-full px-3 py-2 bg-white border border-slate-300 rounded text-sm"
                                        >
                                            <option value="">Không có vật phẩm thưởng</option>
                                            {items.map((entry) => (
                                                <option key={entry._id} value={entry._id}>{entry.name}</option>
                                            ))}
                                        </select>
                                        {form.prizeItemId && (
                                            <div className="mt-2 flex items-center gap-2">
                                                <input
                                                    type="number"
                                                    min="1"
                                                    value={form.prizeItemQuantity}
                                                    onChange={(e) => setForm({ ...form, prizeItemQuantity: Math.max(1, Number.parseInt(e.target.value, 10) || 1) })}
                                                    className="w-24 px-3 py-2 bg-white border border-slate-300 rounded text-sm"
                                                />
                                                <span className="text-xs text-slate-500">Số lượng</span>
                                            </div>
                                        )}
                                        {selectedPrizeItem && (
                                            <div className="mt-2 text-xs text-slate-600">Đã chọn: {selectedPrizeItem.name}</div>
                                        )}
                                    </div>
                                    <div>
                                        <label className="block text-slate-700 text-xs font-bold mb-1.5 uppercase">🪙 Xu Bạch Kim</label>
                                        <input
                                            type="number"
                                            min="0"
                                            value={form.platinumCoinsReward}
                                            onChange={(e) => setForm({ ...form, platinumCoinsReward: parseInt(e.target.value) || 0 })}
                                            className="w-full px-3 py-2 bg-white border border-slate-300 rounded text-sm"
                                            placeholder="0"
                                        />
                                    </div>
                                    <div>
                                        <label className="block text-slate-700 text-xs font-bold mb-1.5 uppercase">⭐ EXP Huấn Luyện Viên</label>
                                        <input
                                            type="number"
                                            min="0"
                                            value={form.expReward}
                                            onChange={(e) => setForm({ ...form, expReward: parseInt(e.target.value) || 0 })}
                                            className="w-full px-3 py-2 bg-white border border-slate-300 rounded text-sm"
                                            placeholder="0 = dùng công thức mặc định"
                                        />
                                    </div>
                                    <div>
                                        <label className="block text-slate-700 text-xs font-bold mb-1.5 uppercase">🌑 Điểm Nguyệt Các</label>
                                        <input
                                            type="number"
                                            min="0"
                                            value={form.moonPointsReward}
                                            onChange={(e) => setForm({ ...form, moonPointsReward: parseInt(e.target.value) || 0 })}
                                            className="w-full px-3 py-2 bg-white border border-slate-300 rounded text-sm"
                                            placeholder="0 = dùng công thức mặc định"
                                        />
                                    </div>
                                </div>
                                <div>
                                    <div className="flex items-center justify-between mb-2">
                                        <label className="block text-slate-700 text-xs font-bold uppercase">Đội hình</label>
                                        <div className="flex gap-2">
                                            <button
                                                type="button"
                                                onClick={() => setForm((prev) => ({ ...prev, team: buildRandomTeam() }))}
                                                className="px-2 py-1 text-xs font-bold bg-emerald-600 text-white rounded"
                                            >
                                                Random đội hình
                                            </button>
                                            <button
                                                type="button"
                                                onClick={handleAddTeam}
                                                className="px-2 py-1 text-xs font-bold bg-blue-600 text-white rounded"
                                            >
                                                + Thêm Pokémon
                                            </button>
                                        </div>
                                    </div>
                                    <div className="space-y-2">
                                        {form.team.map((entry, index) => {
                                            const selectedPokemon = pokemon.find((p) => p._id === entry.pokemonId)
                                                || teamPokemonLookup[entry.pokemonId]
                                                || null
                                            const selectedForms = selectedPokemon ? getPokemonFormsForDisplay(selectedPokemon) : []
                                            const normalizedFormId = normalizePokemonFormId(entry.formId)
                                            const selectedForm = selectedForms.find((row) => row.formId === normalizedFormId)
                                                || selectedForms[0]
                                                || null

                                            return (
                                                <div key={index} className="grid grid-cols-1 md:grid-cols-4 gap-2">
                                                    <button
                                                        type="button"
                                                        onClick={() => handleOpenTeamPokemonModal(index)}
                                                        className="px-3 py-2 bg-white border border-slate-300 rounded text-sm text-left hover:border-blue-400 transition-colors"
                                                    >
                                                        {selectedPokemon
                                                            ? `#${String(selectedPokemon.pokedexNumber || 0).padStart(3, '0')} - ${selectedPokemon.name}${selectedForm && !selectedForm.isDefault ? ` (${selectedForm.formName || selectedForm.formId})` : ''}`
                                                            : 'Chọn Pokémon đội hình'}
                                                    </button>
                                                    <input
                                                        type="number"
                                                        min="1"
                                                        value={entry.level}
                                                        onChange={(e) => handleUpdateTeam(index, 'level', parseInt(e.target.value, 10) || 1)}
                                                        className="px-2 py-2 border border-slate-300 rounded text-sm"
                                                    />
                                                    <div className="px-2 py-1 border border-slate-200 rounded bg-white flex items-center justify-between gap-2 min-h-[38px]">
                                                        {selectedPokemon ? (
                                                            <>
                                                                <div className="flex items-center gap-2 min-w-0">
                                                                    <img
                                                                        src={selectedForm?.resolvedImageUrl || getPokemonImageUrl(selectedPokemon)}
                                                                        alt={selectedPokemon.name}
                                                                        className="w-7 h-7 object-contain pixelated shrink-0"
                                                                    />
                                                                    <span className="text-[11px] text-slate-600 truncate">
                                                                        {selectedForm?.formName || selectedForm?.formId || 'normal'}
                                                                    </span>
                                                                </div>
                                                                <button
                                                                    type="button"
                                                                    onClick={() => handleClearTeamPokemon(index)}
                                                                    className="px-1.5 py-0.5 text-[10px] font-bold bg-red-50 border border-red-200 text-red-700 rounded shrink-0"
                                                                >
                                                                    Bỏ
                                                                </button>
                                                            </>
                                                        ) : (
                                                            <span className="text-[11px] text-slate-400">Chưa chọn Pokémon</span>
                                                        )}
                                                    </div>
                                                    <button
                                                        type="button"
                                                        onClick={() => handleRemoveTeam(index)}
                                                        className="px-2 py-1 text-xs font-bold bg-red-500 text-white rounded"
                                                    >
                                                        Xóa
                                                    </button>
                                                </div>
                                            )
                                        })}
                                    </div>
                                </div>
                                <div className="flex gap-2">
                                    <button
                                        type="submit"
                                        className="px-4 py-2 bg-blue-600 text-white font-bold rounded"
                                    >
                                        {editingId ? 'Lưu trainer' : 'Tạo trainer'}
                                    </button>
                                    {editingId ? (
                                        <button
                                            type="button"
                                            onClick={resetForm}
                                            className="px-4 py-2 bg-white border border-slate-300 rounded font-bold"
                                        >
                                            Hủy
                                        </button>
                                    ) : (
                                        <button
                                            type="button"
                                            onClick={() => setShowCreateTrainerForm(false)}
                                            className="px-4 py-2 bg-white border border-slate-300 rounded font-bold"
                                        >
                                            Thu gọn
                                        </button>
                                    )}
                                </div>
                            </form>
                        </div>
                    </div>
                )}
                <div className="mt-6">
                    <div className="mb-2 flex items-center justify-between gap-2 flex-wrap">
                        <div className="text-sm font-bold text-slate-700">
                            Danh sách trainer ({trainerPagination.total})
                            {trainerPagination.total > 0 && (
                                <span className="ml-1 text-xs text-slate-500 font-medium">
                                    [{trainerPageStart}-{trainerPageEnd}]
                                </span>
                            )}
                        </div>
                        <div className="flex items-center gap-2">
                            <button
                                type="button"
                                onClick={handleDeleteAutoGenerated}
                                disabled={deletingAutoGenerated || deletingAll || loading || autoGeneratedTrainerCount === 0}
                                className="px-3 py-1.5 text-xs font-bold bg-amber-600 hover:bg-amber-700 text-white rounded disabled:opacity-50 disabled:cursor-not-allowed"
                            >
                                {deletingAutoGenerated
                                    ? 'Đang xóa auto...'
                                    : `Xóa trainer auto (${autoGeneratedTrainerCount})`}
                            </button>
                            <button
                                type="button"
                                onClick={handleDeleteAll}
                                disabled={deletingAll || deletingAutoGenerated || loading || trainerPagination.total === 0}
                                className="px-3 py-1.5 text-xs font-bold bg-red-600 hover:bg-red-700 text-white rounded disabled:opacity-50 disabled:cursor-not-allowed"
                            >
                                {deletingAll ? 'Đang xóa tất cả...' : 'Xóa toàn bộ trainer'}
                            </button>
                        </div>
                    </div>
                    {loading ? (
                        <div className="text-sm text-slate-500">Đang tải...</div>
                    ) : (
                        <div className="space-y-3">
                            {trainers.length === 0 && (
                                <div className="text-sm text-slate-500 border border-dashed border-slate-300 rounded p-4 text-center">
                                    Chưa có trainer nào ở trang hiện tại.
                                </div>
                            )}
                            {trainers.map((trainer) => (
                                <div key={trainer._id} className="border border-slate-200 rounded p-3 flex flex-col md:flex-row md:items-center md:justify-between gap-3">
                                    <div className="flex items-start gap-3">
                                        {trainer.imageUrl ? (
                                            <img src={trainer.imageUrl} className="w-12 h-12 object-contain pixelated" />
                                        ) : (
                                            <div className="w-12 h-12 bg-slate-100 border border-slate-200 rounded" />
                                        )}
                                        <div>
                                            <div className="font-bold text-slate-800 flex items-center gap-2 flex-wrap">
                                                <span>{trainer.name}</span>
                                                {trainer.autoGenerated && (
                                                    <span className="px-1.5 py-0.5 rounded text-[10px] font-bold bg-emerald-100 text-emerald-700 border border-emerald-200">
                                                        AUTO {trainer.milestoneLevel ? `Lv ${trainer.milestoneLevel}` : ''}
                                                    </span>
                                                )}
                                            </div>
                                            <div className="text-xs text-slate-500">{trainer.team?.length || 0} Pokémon • Order: {trainer.orderIndex ?? 0}</div>
                                            <div className="mt-1.5 text-[11px] text-slate-700 space-y-0.5">
                                                <div>
                                                    Pokémon thưởng: {trainer.prizePokemonId?.name
                                                        ? `${trainer.prizePokemonId.name}${trainer.prizePokemonFormId && trainer.prizePokemonFormId !== 'normal' ? ` (${trainer.prizePokemonFormId})` : ''}`
                                                        : 'Không có'}
                                                </div>
                                                <div>
                                                    Cấp Pokémon thưởng: {Math.max(0, Number(trainer.prizePokemonLevel) || 0) > 0
                                                        ? `Lv ${Math.max(1, Number(trainer.prizePokemonLevel) || 1)}`
                                                        : 'Auto Lv 5'}
                                                </div>
                                                <div>
                                                    Item thưởng: {trainer.prizeItemId?.name
                                                        ? `${trainer.prizeItemId.name} x${Math.max(1, Number(trainer.prizeItemQuantity) || 1)}`
                                                        : 'Không có'}
                                                </div>
                                                <div>
                                                    Thưởng: +{Math.max(0, Number(trainer.platinumCoinsReward) || 0)} Xu • +{Math.max(0, Number(trainer.expReward) || 0)} EXP • +{Math.max(0, Number(trainer.moonPointsReward) || 0)} Nguyệt Các
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="flex gap-2">
                                        <button
                                            onClick={() => handleEdit(trainer)}
                                            className="px-2 py-1 text-xs font-bold bg-green-600 text-white rounded"
                                        >
                                            Sửa / Setup
                                        </button>
                                        <button
                                            onClick={() => handleDelete(trainer._id)}
                                            className="px-2 py-1 text-xs font-bold bg-red-500 text-white rounded"
                                        >
                                            Xóa
                                        </button>
                                    </div>
                                </div>
                            ))}
                            {trainerPagination.pages > 1 && (
                                <div className="pt-2 flex flex-wrap items-center justify-center gap-1.5">
                                    <button
                                        type="button"
                                        onClick={() => setTrainerPagination((prev) => ({ ...prev, page: Math.max(1, prev.page - 1) }))}
                                        disabled={trainerPagination.page <= 1 || loading}
                                        className="px-2 py-1 text-xs font-bold rounded border border-slate-300 bg-white text-slate-700 disabled:opacity-40 disabled:cursor-not-allowed"
                                    >
                                        Trước
                                    </button>
                                    {trainerPageItems.map((item, index) => (
                                        item === '...'
                                            ? <span key={`trainer-ellipsis-${index}`} className="px-1 text-xs text-slate-400">...</span>
                                            : (
                                                <button
                                                    key={`trainer-page-${item}`}
                                                    type="button"
                                                    onClick={() => setTrainerPagination((prev) => ({ ...prev, page: item }))}
                                                    className={`min-w-[32px] px-2 py-1 text-xs font-bold rounded border ${item === trainerPagination.page
                                                        ? 'bg-blue-600 text-white border-blue-700'
                                                        : 'bg-white text-slate-700 border-slate-300 hover:bg-blue-50 hover:border-blue-300'}`}
                                                >
                                                    {item}
                                                </button>
                                            )
                                    ))}
                                    <button
                                        type="button"
                                        onClick={() => setTrainerPagination((prev) => ({
                                            ...prev,
                                            page: Math.min(prev.pages, prev.page + 1),
                                        }))}
                                        disabled={trainerPagination.page >= trainerPagination.pages || loading}
                                        className="px-2 py-1 text-xs font-bold rounded border border-slate-300 bg-white text-slate-700 disabled:opacity-40 disabled:cursor-not-allowed"
                                    >
                                        Sau
                                    </button>
                                </div>
                            )}
                        </div>
                    )}
                </div>
            </div>

            <div className="text-center mt-6 p-4">
                <Link
                    to="/admin"
                    className="inline-block px-4 py-2 bg-slate-600 hover:bg-slate-700 text-white rounded font-bold shadow-sm"
                >
                    ← Quay lại Dashboard
                </Link>
            </div>

            {showPrizePokemonModal && (
                <div
                    className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm flex items-center justify-center z-[60] p-4 animate-fadeIn"
                    onClick={() => setShowPrizePokemonModal(false)}
                >
                    <div
                        className="bg-white rounded-lg border border-slate-200 p-4 sm:p-6 w-full max-w-[94vw] sm:max-w-2xl shadow-2xl max-h-[92vh] overflow-y-auto"
                        onClick={(e) => e.stopPropagation()}
                    >
                        <div className="flex justify-between items-center mb-4 border-b border-slate-100 pb-3">
                            <h3 className="text-lg font-bold text-slate-800">Chọn Pokemon phần thưởng</h3>
                            <button
                                type="button"
                                onClick={() => setShowPrizePokemonModal(false)}
                                className="text-slate-400 hover:text-slate-600 transition-colors"
                            >
                                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                    <path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clipRule="evenodd" />
                                </svg>
                            </button>
                        </div>

                        <div className="space-y-3">
                            <div>
                                <label className="block text-slate-700 text-sm font-bold mb-1.5">Tìm Pokemon</label>
                                <input
                                    type="text"
                                    value={prizePokemonSearchTerm}
                                    onChange={(e) => {
                                        setPrizePokemonSearchTerm(e.target.value)
                                        setPrizePokemonPage(1)
                                        setPrizePokemonFormPage(1)
                                    }}
                                    placeholder="Nhập tên hoặc số Pokedex #"
                                    className="w-full px-3 py-2 bg-white border border-slate-300 rounded-md text-slate-700 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent shadow-sm"
                                />
                            </div>

                            <div className="max-h-80 overflow-y-auto border border-slate-200 rounded-md divide-y divide-slate-100">
                                <button
                                    type="button"
                                    onClick={() => handleSelectPrizePokemon('', 'normal')}
                                    className={`w-full px-3 py-2 text-left text-sm font-semibold transition-colors ${!form.prizePokemonId ? 'bg-emerald-50 text-emerald-700' : 'hover:bg-slate-50 text-slate-700'}`}
                                >
                                    Không có Pokemon phần thưởng
                                </button>

                                {prizePokemonLoading ? (
                                    <div className="px-3 py-4 text-sm text-slate-500 text-center">Đang tải danh sách Pokemon...</div>
                                ) : prizePokemonLoadError ? (
                                    <div className="px-3 py-4 text-sm text-red-600 text-center">{prizePokemonLoadError}</div>
                                ) : prizePokemonFormRows.length === 0 ? (
                                    <div className="px-3 py-4 text-sm text-slate-500 text-center">Không tìm thấy Pokemon phù hợp</div>
                                ) : (
                                    prizePokemonFormRows.map((row) => {
                                        const { pokemon: entry, form: rowForm } = row
                                        const isSelected = form.prizePokemonId === entry._id
                                            && normalizedPrizePokemonFormId === rowForm.formId
                                        return (
                                            <button
                                                key={row.key}
                                                type="button"
                                                onClick={() => handleSelectPrizePokemon(entry._id, rowForm.formId)}
                                                className={`w-full px-3 py-2 text-left flex items-center gap-3 transition-colors ${isSelected ? 'bg-blue-50' : 'hover:bg-slate-50'}`}
                                            >
                                                <div className="w-10 h-10 flex-shrink-0 rounded border border-slate-200 bg-slate-50 flex items-center justify-center overflow-hidden">
                                                    <img
                                                        src={rowForm.resolvedImageUrl || getPokemonImageUrl(entry)}
                                                        alt={entry.name}
                                                        className="w-8 h-8 object-contain pixelated"
                                                    />
                                                </div>
                                                <div className="min-w-0 flex-1">
                                                    <div className="flex items-center gap-2 min-w-0">
                                                        <span className="font-mono text-xs text-slate-500 flex-shrink-0">#{String(entry.pokedexNumber || 0).padStart(3, '0')}</span>
                                                        <span className="font-semibold text-slate-700 truncate">{entry.name}</span>
                                                    </div>
                                                    <div className="mt-1">
                                                        <span className={`px-1.5 py-0.5 rounded-[3px] text-[10px] font-bold uppercase tracking-wide border ${rowForm.isDefault
                                                            ? 'bg-slate-100 text-slate-700 border-slate-200'
                                                            : 'bg-blue-100 text-blue-700 border-blue-200'}`}>
                                                            {rowForm.formName || rowForm.formId}
                                                        </span>
                                                    </div>
                                                </div>
                                                {isSelected && (
                                                    <span className="text-[11px] font-bold text-blue-700 bg-blue-100 border border-blue-200 rounded px-2 py-0.5">Đã chọn</span>
                                                )}
                                            </button>
                                        )
                                    })
                                )}
                            </div>

                            <div className="space-y-2 text-xs text-slate-500">
                                <div className="flex items-center justify-between gap-2 flex-wrap">
                                    <span>
                                        Dạng: {prizePokemonFormPageStart}-{prizePokemonFormPageEnd} / {prizePokemonFormTotal}
                                    </span>
                                    <div className="flex items-center gap-2">
                                        <button
                                            type="button"
                                            onClick={() => setPrizePokemonFormPage((prev) => Math.max(1, prev - 1))}
                                            disabled={safePrizePokemonFormPage <= 1 || prizePokemonLoading}
                                            className="px-2 py-1 rounded border border-slate-300 bg-white text-slate-700 disabled:opacity-40 disabled:cursor-not-allowed"
                                        >
                                            Trước dạng
                                        </button>
                                        <span className="font-semibold text-slate-600">
                                            Trang dạng {safePrizePokemonFormPage}/{prizePokemonFormTotalPages}
                                        </span>
                                        <button
                                            type="button"
                                            onClick={() => setPrizePokemonFormPage((prev) => Math.min(prizePokemonFormTotalPages, prev + 1))}
                                            disabled={safePrizePokemonFormPage >= prizePokemonFormTotalPages || prizePokemonLoading}
                                            className="px-2 py-1 rounded border border-slate-300 bg-white text-slate-700 disabled:opacity-40 disabled:cursor-not-allowed"
                                        >
                                            Sau dạng
                                        </button>
                                    </div>
                                </div>

                                <div className="flex items-center justify-between gap-2 flex-wrap">
                                    <span>
                                        Loài: {prizePokemonPageStart}-{prizePokemonPageEnd} / {prizePokemonTotal}
                                    </span>
                                    <div className="flex items-center gap-2">
                                        <button
                                            type="button"
                                            onClick={() => {
                                                setPrizePokemonPage((prev) => Math.max(1, prev - 1))
                                                setPrizePokemonFormPage(1)
                                            }}
                                            disabled={prizePokemonPage <= 1 || prizePokemonLoading}
                                            className="px-2 py-1 rounded border border-slate-300 bg-white text-slate-700 disabled:opacity-40 disabled:cursor-not-allowed"
                                        >
                                            Trước loài
                                        </button>
                                        <span className="font-semibold text-slate-600">
                                            Trang loài {prizePokemonPage}/{prizePokemonTotalPages}
                                        </span>
                                        <button
                                            type="button"
                                            onClick={() => {
                                                setPrizePokemonPage((prev) => Math.min(prizePokemonTotalPages, prev + 1))
                                                setPrizePokemonFormPage(1)
                                            }}
                                            disabled={prizePokemonPage >= prizePokemonTotalPages || prizePokemonLoading}
                                            className="px-2 py-1 rounded border border-slate-300 bg-white text-slate-700 disabled:opacity-40 disabled:cursor-not-allowed"
                                        >
                                            Sau loài
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {showTeamPokemonModal && (
                <div
                    className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm flex items-center justify-center z-[70] p-4 animate-fadeIn"
                    onClick={() => {
                        setShowTeamPokemonModal(false)
                        setTeamPokemonTargetIndex(-1)
                    }}
                >
                    <div
                        className="bg-white rounded-lg border border-slate-200 p-4 sm:p-6 w-full max-w-[94vw] sm:max-w-2xl shadow-2xl max-h-[92vh] overflow-y-auto"
                        onClick={(e) => e.stopPropagation()}
                    >
                        <div className="flex justify-between items-center mb-4 border-b border-slate-100 pb-3">
                            <div>
                                <h3 className="text-lg font-bold text-slate-800">Chọn Pokémon đội hình</h3>
                                <p className="text-xs text-slate-500 mt-0.5">Slot #{Math.max(1, Number(teamPokemonTargetIndex) + 1)}</p>
                            </div>
                            <button
                                type="button"
                                onClick={() => {
                                    setShowTeamPokemonModal(false)
                                    setTeamPokemonTargetIndex(-1)
                                }}
                                className="text-slate-400 hover:text-slate-600 transition-colors"
                            >
                                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                    <path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clipRule="evenodd" />
                                </svg>
                            </button>
                        </div>

                        <div className="space-y-3">
                            <div>
                                <label className="block text-slate-700 text-sm font-bold mb-1.5">Tìm Pokémon đội hình</label>
                                <input
                                    type="text"
                                    value={teamPokemonSearchTerm}
                                    onChange={(e) => {
                                        setTeamPokemonSearchTerm(e.target.value)
                                        setTeamPokemonPage(1)
                                        setTeamPokemonFormPage(1)
                                    }}
                                    placeholder="Nhập tên hoặc số Pokedex #"
                                    className="w-full px-3 py-2 bg-white border border-slate-300 rounded-md text-slate-700 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent shadow-sm"
                                />
                            </div>

                            <div className="max-h-80 overflow-y-auto border border-slate-200 rounded-md divide-y divide-slate-100">
                                <button
                                    type="button"
                                    onClick={() => handleSelectTeamPokemon('', 'normal')}
                                    className={`w-full px-3 py-2 text-left text-sm font-semibold transition-colors ${!activeTeamEntry?.pokemonId ? 'bg-emerald-50 text-emerald-700' : 'hover:bg-slate-50 text-slate-700'}`}
                                >
                                    Không chọn Pokémon cho slot này
                                </button>

                                {teamPokemonLoading ? (
                                    <div className="px-3 py-4 text-sm text-slate-500 text-center">Đang tải danh sách Pokémon...</div>
                                ) : teamPokemonLoadError ? (
                                    <div className="px-3 py-4 text-sm text-red-600 text-center">{teamPokemonLoadError}</div>
                                ) : teamPokemonFormRows.length === 0 ? (
                                    <div className="px-3 py-4 text-sm text-slate-500 text-center">Không tìm thấy Pokémon phù hợp</div>
                                ) : (
                                    teamPokemonFormRows.map((row) => {
                                        const { pokemon: entry, form: rowForm } = row
                                        const isSelected = activeTeamEntry?.pokemonId === entry._id
                                            && normalizedTeamPokemonFormId === rowForm.formId
                                        return (
                                            <button
                                                key={`team-${row.key}`}
                                                type="button"
                                                onClick={() => handleSelectTeamPokemon(entry._id, rowForm.formId)}
                                                className={`w-full px-3 py-2 text-left flex items-center gap-3 transition-colors ${isSelected ? 'bg-blue-50' : 'hover:bg-slate-50'}`}
                                            >
                                                <div className="w-10 h-10 flex-shrink-0 rounded border border-slate-200 bg-slate-50 flex items-center justify-center overflow-hidden">
                                                    <img
                                                        src={rowForm.resolvedImageUrl || getPokemonImageUrl(entry)}
                                                        alt={entry.name}
                                                        className="w-8 h-8 object-contain pixelated"
                                                    />
                                                </div>
                                                <div className="min-w-0 flex-1">
                                                    <div className="flex items-center gap-2 min-w-0">
                                                        <span className="font-mono text-xs text-slate-500 flex-shrink-0">#{String(entry.pokedexNumber || 0).padStart(3, '0')}</span>
                                                        <span className="font-semibold text-slate-700 truncate">{entry.name}</span>
                                                    </div>
                                                    <div className="mt-1">
                                                        <span className={`px-1.5 py-0.5 rounded-[3px] text-[10px] font-bold uppercase tracking-wide border ${rowForm.isDefault
                                                            ? 'bg-slate-100 text-slate-700 border-slate-200'
                                                            : 'bg-blue-100 text-blue-700 border-blue-200'}`}>
                                                            {rowForm.formName || rowForm.formId}
                                                        </span>
                                                    </div>
                                                </div>
                                                {isSelected && (
                                                    <span className="text-[11px] font-bold text-blue-700 bg-blue-100 border border-blue-200 rounded px-2 py-0.5">Đã chọn</span>
                                                )}
                                            </button>
                                        )
                                    })
                                )}
                            </div>

                            <div className="space-y-2 text-xs text-slate-500">
                                <div className="flex items-center justify-between gap-2 flex-wrap">
                                    <span>
                                        Dạng: {teamPokemonFormPageStart}-{teamPokemonFormPageEnd} / {teamPokemonFormTotal}
                                    </span>
                                    <div className="flex items-center gap-2">
                                        <button
                                            type="button"
                                            onClick={() => setTeamPokemonFormPage((prev) => Math.max(1, prev - 1))}
                                            disabled={safeTeamPokemonFormPage <= 1 || teamPokemonLoading}
                                            className="px-2 py-1 rounded border border-slate-300 bg-white text-slate-700 disabled:opacity-40 disabled:cursor-not-allowed"
                                        >
                                            Trước dạng
                                        </button>
                                        <span className="font-semibold text-slate-600">
                                            Trang dạng {safeTeamPokemonFormPage}/{teamPokemonFormTotalPages}
                                        </span>
                                        <button
                                            type="button"
                                            onClick={() => setTeamPokemonFormPage((prev) => Math.min(teamPokemonFormTotalPages, prev + 1))}
                                            disabled={safeTeamPokemonFormPage >= teamPokemonFormTotalPages || teamPokemonLoading}
                                            className="px-2 py-1 rounded border border-slate-300 bg-white text-slate-700 disabled:opacity-40 disabled:cursor-not-allowed"
                                        >
                                            Sau dạng
                                        </button>
                                    </div>
                                </div>

                                <div className="flex items-center justify-between gap-2 flex-wrap">
                                    <span>
                                        Loài: {teamPokemonPageStart}-{teamPokemonPageEnd} / {teamPokemonTotal}
                                    </span>
                                    <div className="flex items-center gap-2">
                                        <button
                                            type="button"
                                            onClick={() => {
                                                setTeamPokemonPage((prev) => Math.max(1, prev - 1))
                                                setTeamPokemonFormPage(1)
                                            }}
                                            disabled={teamPokemonPage <= 1 || teamPokemonLoading}
                                            className="px-2 py-1 rounded border border-slate-300 bg-white text-slate-700 disabled:opacity-40 disabled:cursor-not-allowed"
                                        >
                                            Trước loài
                                        </button>
                                        <span className="font-semibold text-slate-600">
                                            Trang loài {teamPokemonPage}/{teamPokemonTotalPages}
                                        </span>
                                        <button
                                            type="button"
                                            onClick={() => {
                                                setTeamPokemonPage((prev) => Math.min(teamPokemonTotalPages, prev + 1))
                                                setTeamPokemonFormPage(1)
                                            }}
                                            disabled={teamPokemonPage >= teamPokemonTotalPages || teamPokemonLoading}
                                            className="px-2 py-1 rounded border border-slate-300 bg-white text-slate-700 disabled:opacity-40 disabled:cursor-not-allowed"
                                        >
                                            Sau loài
                                        </button>
                                    </div>
                                </div>
                            </div>

                            {selectedTeamPokemon && (
                                <div className="rounded border border-slate-200 bg-slate-50 px-3 py-2 text-xs text-slate-600">
                                    Đang chọn cho slot này: <span className="font-bold text-slate-800">{selectedTeamPokemon.name}</span>
                                    {selectedTeamPokemonForm && (
                                        <span className="ml-1">({selectedTeamPokemonForm.formName || selectedTeamPokemonForm.formId})</span>
                                    )}
                                </div>
                            )}
                        </div>
                    </div>
                </div>
            )}
        </div>
    )
}
