import dotenv from 'dotenv'
import mongoose from 'mongoose'
import { connectDB } from '../config/db.js'
import BattleTrainer from '../models/BattleTrainer.js'

dotenv.config()

const SNAPSHOT_COLLECTION = 'maintenance_snapshots'
const SNAPSHOT_TYPE = 'battle-trainer-team-levels'

const args = process.argv.slice(2)
const argSet = new Set(args)

const isDryRun = argSet.has('--dry-run')
const includeManual = argSet.has('--include-manual')
const forceAllLevels = argSet.has('--all-levels')
const allowOverwrite = argSet.has('--overwrite')

const parseArgValue = (name, fallback = '') => {
    const prefix = `--${name}=`
    const raw = args.find((entry) => String(entry || '').startsWith(prefix))
    if (!raw) return fallback
    return String(raw.slice(prefix.length) || '').trim()
}

const parsePositiveInt = (value, fallback = 1) => {
    const parsed = Number.parseInt(value, 10)
    if (!Number.isFinite(parsed) || parsed < 1) return fallback
    return parsed
}

const minLevel = forceAllLevels
    ? 1
    : parsePositiveInt(parseArgValue('min-level', '1001'), 1001)

const levelSource = (() => {
    const raw = parseArgValue('source', 'max').toLowerCase()
    if (raw === 'milestone' || raw === 'order' || raw === 'max') return raw
    return 'max'
})()

const snapshotTag = (() => {
    const rawTag = parseArgValue('tag', '')
    if (rawTag) return rawTag
    return `auto-trainer-levels-${Date.now()}`
})()

const resolveTrainerLevel = (trainer = {}) => {
    const milestoneLevel = Math.max(0, Number.parseInt(trainer?.milestoneLevel, 10) || 0)
    const orderLevel = Math.max(0, Number.parseInt(trainer?.orderIndex, 10) || 0)

    if (levelSource === 'milestone') return milestoneLevel
    if (levelSource === 'order') return orderLevel
    return Math.max(milestoneLevel, orderLevel)
}

const run = async () => {
    try {
        await connectDB()

        const levelFilter = { $gte: minLevel }
        const baseQuery = {
            $or: [
                { milestoneLevel: levelFilter },
                { orderIndex: levelFilter },
            ],
        }

        const query = includeManual
            ? baseQuery
            : {
                autoGenerated: true,
                ...baseQuery,
            }

        const trainers = await BattleTrainer.find(query)
            .select('_id name autoGenerated orderIndex milestoneLevel team')
            .lean()

        const rows = trainers.map((trainer) => {
            const team = Array.isArray(trainer?.team) ? trainer.team : []
            const teamLevels = team.map((entry) => Math.max(1, Number.parseInt(entry?.level, 10) || 1))
            const normalizedTeam = team.map((entry) => ({
                pokemonId: String(entry?.pokemonId || '').trim(),
                level: Math.max(1, Number.parseInt(entry?.level, 10) || 1),
                formId: String(entry?.formId || 'normal').trim().toLowerCase() || 'normal',
                damagePercent: Math.max(0, Number.parseInt(entry?.damagePercent, 10) || 100),
            }))

            return {
                trainerId: String(trainer?._id || ''),
                name: String(trainer?.name || '').trim() || 'Trainer',
                autoGenerated: Boolean(trainer?.autoGenerated),
                orderIndex: Math.max(0, Number.parseInt(trainer?.orderIndex, 10) || 0),
                milestoneLevel: Math.max(0, Number.parseInt(trainer?.milestoneLevel, 10) || 0),
                resolvedTrainerLevel: resolveTrainerLevel(trainer),
                teamLevels,
                team: normalizedTeam,
            }
        })

        const totalTeamEntries = rows.reduce(
            (sum, row) => sum + (Array.isArray(row.teamLevels) ? row.teamLevels.length : 0),
            0
        )

        console.log('=== Create Trainer Team Levels Snapshot ===')
        console.log(`Tag: ${snapshotTag}`)
        console.log(`Mode: ${includeManual ? 'all trainers' : 'auto-generated only'}`)
        console.log(`Source level: ${levelSource}`)
        console.log(`Minimum trainer level: ${minLevel}`)
        console.log(`Dry run: ${isDryRun ? 'yes' : 'no'}`)
        console.log(`Trainers in snapshot: ${rows.length}`)
        console.log(`Team entries in snapshot: ${totalTeamEntries}`)

        if (rows.length > 0) {
            console.log('Preview (first 10):')
            rows.slice(0, 10).forEach((row, index) => {
                console.log(
                    `${index + 1}. ${row.name} (${row.trainerId}) | level ${row.resolvedTrainerLevel} | slots: ${row.teamLevels.length}`
                )
            })
        }

        if (isDryRun) {
            console.log('Dry run complete. No data was modified.')
            return
        }

        const snapshotCollection = mongoose.connection.collection(SNAPSHOT_COLLECTION)
        const existing = await snapshotCollection.findOne({
            type: SNAPSHOT_TYPE,
            tag: snapshotTag,
        })

        if (existing && !allowOverwrite) {
            throw new Error(`Tag already exists: ${snapshotTag}. Use --overwrite or another --tag.`)
        }

        const snapshotDoc = {
            type: SNAPSHOT_TYPE,
            tag: snapshotTag,
            createdAt: new Date(),
            config: {
                includeManual,
                minLevel,
                levelSource,
            },
            trainerCount: rows.length,
            teamEntryCount: totalTeamEntries,
            trainers: rows,
        }

        await snapshotCollection.updateOne(
            {
                type: SNAPSHOT_TYPE,
                tag: snapshotTag,
            },
            {
                $set: snapshotDoc,
            },
            { upsert: true }
        )

        console.log('Snapshot saved.')
        console.log(`Collection: ${SNAPSHOT_COLLECTION}`)
        console.log(`Tag: ${snapshotTag}`)
    } catch (error) {
        console.error('Snapshot failed:', error.message)
        process.exitCode = 1
    } finally {
        await mongoose.disconnect()
    }
}

run()
