import dotenv from 'dotenv'
import mongoose from 'mongoose'
import { connectDB } from '../config/db.js'
import BattleTrainer from '../models/BattleTrainer.js'

dotenv.config()

const args = process.argv.slice(2)
const argSet = new Set(args)

const isDryRun = argSet.has('--dry-run')
const includeManual = argSet.has('--include-manual')
const forceAllLevels = argSet.has('--all-levels')

const parseArgValue = (name, fallback = '') => {
    const prefix = `--${name}=`
    const raw = args.find((entry) => String(entry || '').startsWith(prefix))
    if (!raw) return fallback
    return String(raw.slice(prefix.length) || '').trim()
}

const parsePositiveInt = (value, fallback = 1) => {
    const parsed = Number.parseInt(value, 10)
    if (!Number.isFinite(parsed) || parsed < 1) return fallback
    return parsed
}

const minLevel = forceAllLevels
    ? 1
    : parsePositiveInt(parseArgValue('min-level', '1001'), 1001)

const levelSource = (() => {
    const raw = parseArgValue('source', 'max').toLowerCase()
    if (raw === 'milestone' || raw === 'order' || raw === 'max') return raw
    return 'max'
})()

const resolveTrainerLevel = (trainer = {}) => {
    const milestoneLevel = Math.max(0, Number.parseInt(trainer?.milestoneLevel, 10) || 0)
    const orderLevel = Math.max(0, Number.parseInt(trainer?.orderIndex, 10) || 0)

    if (levelSource === 'milestone') return milestoneLevel
    if (levelSource === 'order') return orderLevel
    return Math.max(milestoneLevel, orderLevel)
}

const run = async () => {
    try {
        await connectDB()

        const levelFilter = { $gte: minLevel }
        const baseQuery = {
            $or: [
                { milestoneLevel: levelFilter },
                { orderIndex: levelFilter },
            ],
        }

        const query = includeManual
            ? baseQuery
            : {
                autoGenerated: true,
                ...baseQuery,
            }

        const trainers = await BattleTrainer.find(query)
            .select('_id name autoGenerated orderIndex milestoneLevel team')
            .lean()

        let changedTrainerCount = 0
        let changedPokemonCount = 0
        const bulkOps = []
        const changedPreviewRows = []

        for (const trainer of trainers) {
            const trainerLevel = resolveTrainerLevel(trainer)
            if (trainerLevel < 1) continue

            const team = Array.isArray(trainer?.team) ? trainer.team : []
            if (team.length === 0) continue

            let changedInTrainer = 0
            const nextTeam = team.map((entry) => {
                const currentLevel = Math.max(1, Number.parseInt(entry?.level, 10) || 1)
                if (currentLevel === trainerLevel) return entry
                changedInTrainer += 1
                return {
                    ...entry,
                    level: trainerLevel,
                }
            })

            if (changedInTrainer === 0) continue

            changedTrainerCount += 1
            changedPokemonCount += changedInTrainer

            if (changedPreviewRows.length < 10) {
                changedPreviewRows.push({
                    id: String(trainer?._id || ''),
                    name: String(trainer?.name || '').trim() || 'Trainer',
                    targetLevel: trainerLevel,
                    changedSlots: changedInTrainer,
                    autoGenerated: Boolean(trainer?.autoGenerated),
                })
            }

            bulkOps.push({
                updateOne: {
                    filter: { _id: trainer._id },
                    update: {
                        $set: {
                            team: nextTeam,
                        },
                    },
                },
            })
        }

        console.log('=== Fix Trainer Team Levels By Trainer Level ===')
        console.log(`Mode: ${includeManual ? 'all trainers' : 'auto-generated only'}`)
        console.log(`Source level: ${levelSource}`)
        console.log(`Minimum trainer level: ${minLevel}`)
        console.log(`Dry run: ${isDryRun ? 'yes' : 'no'}`)
        console.log(`Matched trainers: ${trainers.length}`)
        console.log(`Trainers to update: ${changedTrainerCount}`)
        console.log(`Team members to update: ${changedPokemonCount}`)

        if (changedPreviewRows.length > 0) {
            console.log('Preview (first 10):')
            changedPreviewRows.forEach((row, index) => {
                console.log(
                    `${index + 1}. ${row.name} (${row.id}) | level -> ${row.targetLevel} | slots: ${row.changedSlots} | auto: ${row.autoGenerated ? 'yes' : 'no'}`
                )
            })
        }

        if (isDryRun || bulkOps.length === 0) {
            console.log(isDryRun ? 'Dry run complete. No data was modified.' : 'No updates needed.')
            return
        }

        const bulkResult = await BattleTrainer.bulkWrite(bulkOps, { ordered: false })
        console.log('Fix complete.')
        console.log(`Bulk matched: ${bulkResult.matchedCount || 0}`)
        console.log(`Bulk modified: ${bulkResult.modifiedCount || 0}`)
    } catch (error) {
        console.error('Fix failed:', error.message)
        process.exitCode = 1
    } finally {
        await mongoose.disconnect()
    }
}

run()
