import dotenv from 'dotenv'
import mongoose from 'mongoose'
import { connectDB } from '../config/db.js'
import BattleTrainer from '../models/BattleTrainer.js'

dotenv.config()

const args = new Set(process.argv.slice(2))
const isDryRun = args.has('--dry-run')
const autoOnly = args.has('--auto-only')

const run = async () => {
    try {
        await connectDB()

        const targetQuery = autoOnly ? { autoGenerated: true } : {}
        const updateQuery = {
            ...targetQuery,
            moonPointsReward: { $ne: 0 },
        }

        const [totalTrainers, autoGeneratedCount, trainersWithMoonPoints] = await Promise.all([
            BattleTrainer.countDocuments({}),
            BattleTrainer.countDocuments({ autoGenerated: true }),
            BattleTrainer.countDocuments(updateQuery),
        ])

        console.log('=== Battle Trainer Moon Points Reset ===')
        console.log(`Mode: ${autoOnly ? 'auto-generated only' : 'all trainers'}`)
        console.log(`Dry run: ${isDryRun ? 'yes' : 'no'}`)
        console.log(`Total trainers: ${totalTrainers}`)
        console.log(`Auto-generated trainers: ${autoGeneratedCount}`)
        console.log(`Trainers to reset: ${trainersWithMoonPoints}`)

        if (isDryRun) {
            console.log('Dry run complete. No data was modified.')
            return
        }

        const result = await BattleTrainer.updateMany(
            updateQuery,
            {
                $set: { moonPointsReward: 0 },
            }
        )

        console.log('Reset complete.')
        console.log(`Matched: ${result.matchedCount}`)
        console.log(`Modified: ${result.modifiedCount}`)
    } catch (error) {
        console.error('Reset failed:', error.message)
        process.exitCode = 1
    } finally {
        await mongoose.disconnect()
    }
}

run()
