import express from 'express'
import BattleTrainer from '../../models/BattleTrainer.js'
import Pokemon from '../../models/Pokemon.js'
import Item from '../../models/Item.js'

const router = express.Router()

const normalizeFormId = (value) => String(value || '').trim().toLowerCase() || 'normal'

const clampNumber = (value, min, max) => {
    const parsed = Number.parseInt(value, 10)
    if (!Number.isFinite(parsed)) return min
    return Math.min(max, Math.max(min, parsed))
}

const parseRewardNumber = (value, fallback = 0) => {
    if (value === undefined || value === null || value === '') return fallback
    return Math.max(0, Number.parseInt(value, 10) || 0)
}

const parseOptionalRewardNumber = (value) => {
    if (value === undefined || value === null || value === '') return null
    return parseRewardNumber(value, 0)
}

const resolveMoonPointsReward = ({ moonPointsReward, autoGenerated, fallback = 0 }) => {
    if (autoGenerated) return 0
    return parseRewardNumber(moonPointsReward, fallback)
}

const parsePositiveInt = (value, fallback = 1) => {
    const parsed = Number.parseInt(value, 10)
    if (!Number.isFinite(parsed) || parsed < 1) return fallback
    return parsed
}

const parseOptionalPrizeLevel = (value) => {
    if (value === undefined || value === null || value === '') return 0
    return clampNumber(value, 1, 1000)
}

const normalizeTeam = (team) => {
    if (!Array.isArray(team)) return []
    return team
        .map((entry) => ({
            pokemonId: entry?.pokemonId || entry?.pokemon || entry?._id || '',
            level: Number(entry?.level) || 5,
            formId: String(entry?.formId || 'normal').trim(),
        }))
        .filter((entry) => entry.pokemonId)
}

const validateTeam = async (team) => {
    if (!team.length) return null
    const ids = team.map((entry) => entry.pokemonId)
    const count = await Pokemon.countDocuments({ _id: { $in: ids } })
    if (count !== ids.length) return 'Đội hình chứa Pokemon id không hợp lệ'
    return null
}

const resolvePrizePokemonSelection = async (pokemonId, formId) => {
    const normalizedPokemonId = String(pokemonId || '').trim()
    if (!normalizedPokemonId) {
        return {
            prizePokemonId: null,
            prizePokemonFormId: 'normal',
            error: null,
        }
    }

    const prizePokemon = await Pokemon.findById(normalizedPokemonId)
        .select('_id forms defaultFormId')
        .lean()

    if (!prizePokemon) {
        return {
            prizePokemonId: null,
            prizePokemonFormId: 'normal',
            error: 'Pokemon phần thưởng không hợp lệ',
        }
    }

    const forms = Array.isArray(prizePokemon.forms) ? prizePokemon.forms : []
    const defaultFormId = normalizeFormId(prizePokemon.defaultFormId)
    const requestedFormId = normalizeFormId(formId)

    let resolvedFormId = requestedFormId
    if (forms.length > 0) {
        const hasRequestedForm = forms.some((entry) => normalizeFormId(entry?.formId) === requestedFormId)
        if (!hasRequestedForm) {
            const fallbackFormId = normalizeFormId(forms[0]?.formId)
            resolvedFormId = defaultFormId || fallbackFormId || 'normal'
        }
    } else {
        resolvedFormId = defaultFormId || requestedFormId || 'normal'
    }

    return {
        prizePokemonId: prizePokemon._id,
        prizePokemonFormId: resolvedFormId,
        error: null,
    }
}

const resolvePrizeItemSelection = async (itemId, quantity) => {
    const normalizedItemId = String(itemId || '').trim()
    if (!normalizedItemId) {
        return {
            prizeItemId: null,
            prizeItemQuantity: 1,
            error: null,
        }
    }

    const item = await Item.findById(normalizedItemId)
        .select('_id name')
        .lean()
    if (!item) {
        return {
            prizeItemId: null,
            prizeItemQuantity: 1,
            error: 'Vật phẩm phần thưởng không hợp lệ',
        }
    }

    return {
        prizeItemId: item._id,
        prizeItemQuantity: Math.max(1, Number.parseInt(quantity, 10) || 1),
        error: null,
    }
}

const buildAutoTeam = (pokemonPool, level, seed, teamSize = 3) => {
    if (!Array.isArray(pokemonPool) || pokemonPool.length === 0) return []
    const normalizedTeamSize = clampNumber(teamSize, 1, 6)
    const baseIndex = Math.abs(seed) % pokemonPool.length
    const team = []
    for (let slot = 0; slot < normalizedTeamSize; slot += 1) {
        const pickIndex = (baseIndex + slot) % pokemonPool.length
        const selectedPokemon = pokemonPool[pickIndex]
        const adjustedLevel = parsePositiveInt(level, 1)
        const formId = normalizeFormId(selectedPokemon?.defaultFormId || selectedPokemon?.forms?.[0]?.formId || 'normal')
        team.push({
            pokemonId: selectedPokemon._id,
            level: adjustedLevel,
            formId,
        })
    }
    return team
}

const normalizeAutoTrainerMoonPointsRewards = async () => {
    await BattleTrainer.updateMany(
        {
            autoGenerated: true,
            moonPointsReward: { $ne: 0 },
        },
        {
            $set: { moonPointsReward: 0 },
        }
    )
}

// GET /api/admin/battle-trainers
router.get('/', async (req, res) => {
    try {
        await normalizeAutoTrainerMoonPointsRewards()
        const trainers = await BattleTrainer.find()
            .sort({ orderIndex: 1, createdAt: 1 })
            .populate('team.pokemonId', 'name pokedexNumber imageUrl sprites forms defaultFormId')
            .populate('prizePokemonId', 'name pokedexNumber imageUrl sprites forms defaultFormId')
            .populate('prizeItemId', 'name imageUrl type rarity')
            .lean()
        res.json({ ok: true, trainers })
    } catch (error) {
        console.error('GET /api/admin/battle-trainers error:', error)
        res.status(500).json({ ok: false, message: 'Lỗi máy chủ' })
    }
})

// POST /api/admin/battle-trainers
router.post('/', async (req, res) => {
    try {
        const {
            name,
            imageUrl,
            quote,
            isActive,
            orderIndex,
            team,
            prizePokemonId,
            prizePokemonFormId,
            prizePokemonLevel,
            prizeItemId,
            prizeItemQuantity,
            platinumCoinsReward,
            expReward,
            moonPointsReward,
            autoGenerated,
            milestoneLevel,
        } = req.body

        if (!name) {
            return res.status(400).json({ ok: false, message: 'Tên là bắt buộc' })
        }

        const normalizedTeam = normalizeTeam(team)
        const teamError = await validateTeam(normalizedTeam)
        if (teamError) {
            return res.status(400).json({ ok: false, message: teamError })
        }

        const resolvedPrizeSelection = await resolvePrizePokemonSelection(prizePokemonId, prizePokemonFormId)
        if (resolvedPrizeSelection.error) {
            return res.status(400).json({ ok: false, message: resolvedPrizeSelection.error })
        }

        const resolvedPrizeItemSelection = await resolvePrizeItemSelection(prizeItemId, prizeItemQuantity)
        if (resolvedPrizeItemSelection.error) {
            return res.status(400).json({ ok: false, message: resolvedPrizeItemSelection.error })
        }

        const isAutoGeneratedTrainer = Boolean(autoGenerated)

        const trainer = new BattleTrainer({
            name,
            imageUrl: imageUrl || '',
            quote: quote || '',
            isActive: isActive !== undefined ? isActive : true,
            orderIndex: orderIndex !== undefined ? orderIndex : 0,
            team: normalizedTeam,
            prizePokemonId: resolvedPrizeSelection.prizePokemonId,
            prizePokemonFormId: resolvedPrizeSelection.prizePokemonFormId,
            prizePokemonLevel: resolvedPrizeSelection.prizePokemonId
                ? parseOptionalPrizeLevel(prizePokemonLevel)
                : 0,
            prizeItemId: resolvedPrizeItemSelection.prizeItemId,
            prizeItemQuantity: resolvedPrizeItemSelection.prizeItemQuantity,
            platinumCoinsReward: parseRewardNumber(platinumCoinsReward, 0),
            expReward: parseRewardNumber(expReward, 0),
            moonPointsReward: resolveMoonPointsReward({
                moonPointsReward,
                autoGenerated: isAutoGeneratedTrainer,
                fallback: 0,
            }),
            autoGenerated: isAutoGeneratedTrainer,
            milestoneLevel: clampNumber(milestoneLevel, 0, 1000),
        })

        await trainer.save()

        res.status(201).json({ ok: true, trainer })
    } catch (error) {
        console.error('POST /api/admin/battle-trainers error:', error)
        res.status(500).json({ ok: false, message: error.message })
    }
})

// PUT /api/admin/battle-trainers/:id
router.put('/:id', async (req, res) => {
    try {
        const {
            name,
            imageUrl,
            quote,
            isActive,
            orderIndex,
            team,
            prizePokemonId,
            prizePokemonFormId,
            prizePokemonLevel,
            prizeItemId,
            prizeItemQuantity,
            platinumCoinsReward,
            expReward,
            moonPointsReward,
            autoGenerated,
            milestoneLevel,
        } = req.body

        const trainer = await BattleTrainer.findById(req.params.id)
        if (!trainer) {
            return res.status(404).json({ ok: false, message: 'Không tìm thấy huấn luyện viên' })
        }

        const normalizedTeam = normalizeTeam(team)
        const shouldUpdateTeam = team !== undefined
        if (shouldUpdateTeam) {
            const teamError = await validateTeam(normalizedTeam)
            if (teamError) {
                return res.status(400).json({ ok: false, message: teamError })
            }
        }

        if (name !== undefined) trainer.name = name
        if (imageUrl !== undefined) trainer.imageUrl = imageUrl
        if (quote !== undefined) trainer.quote = quote
        if (isActive !== undefined) trainer.isActive = isActive
        if (orderIndex !== undefined) trainer.orderIndex = orderIndex
        if (shouldUpdateTeam) trainer.team = normalizedTeam

        if (prizePokemonId !== undefined || prizePokemonFormId !== undefined) {
            const nextPrizePokemonId = prizePokemonId !== undefined ? prizePokemonId : trainer.prizePokemonId
            const nextPrizePokemonFormId = prizePokemonFormId !== undefined ? prizePokemonFormId : trainer.prizePokemonFormId
            const resolvedPrizeSelection = await resolvePrizePokemonSelection(nextPrizePokemonId, nextPrizePokemonFormId)
            if (resolvedPrizeSelection.error) {
                return res.status(400).json({ ok: false, message: resolvedPrizeSelection.error })
            }
            trainer.prizePokemonId = resolvedPrizeSelection.prizePokemonId
            trainer.prizePokemonFormId = resolvedPrizeSelection.prizePokemonFormId

            if (!resolvedPrizeSelection.prizePokemonId) {
                trainer.prizePokemonLevel = 0
            } else if (prizePokemonLevel !== undefined) {
                trainer.prizePokemonLevel = parseOptionalPrizeLevel(prizePokemonLevel)
            }
        } else if (prizePokemonLevel !== undefined) {
            trainer.prizePokemonLevel = trainer.prizePokemonId
                ? parseOptionalPrizeLevel(prizePokemonLevel)
                : 0
        }

        if (prizeItemId !== undefined || prizeItemQuantity !== undefined) {
            const nextPrizeItemId = prizeItemId !== undefined ? prizeItemId : trainer.prizeItemId
            const nextPrizeItemQuantity = prizeItemQuantity !== undefined ? prizeItemQuantity : trainer.prizeItemQuantity
            const resolvedPrizeItemSelection = await resolvePrizeItemSelection(nextPrizeItemId, nextPrizeItemQuantity)
            if (resolvedPrizeItemSelection.error) {
                return res.status(400).json({ ok: false, message: resolvedPrizeItemSelection.error })
            }
            trainer.prizeItemId = resolvedPrizeItemSelection.prizeItemId
            trainer.prizeItemQuantity = resolvedPrizeItemSelection.prizeItemQuantity
        }

        if (platinumCoinsReward !== undefined) trainer.platinumCoinsReward = parseRewardNumber(platinumCoinsReward, 0)
        if (expReward !== undefined) trainer.expReward = parseRewardNumber(expReward, 0)
        const nextAutoGenerated = autoGenerated !== undefined ? Boolean(autoGenerated) : Boolean(trainer.autoGenerated)
        if (moonPointsReward !== undefined) {
            trainer.moonPointsReward = resolveMoonPointsReward({
                moonPointsReward,
                autoGenerated: nextAutoGenerated,
                fallback: 0,
            })
        } else if (nextAutoGenerated) {
            trainer.moonPointsReward = 0
        }
        if (autoGenerated !== undefined) trainer.autoGenerated = nextAutoGenerated
        if (milestoneLevel !== undefined) trainer.milestoneLevel = clampNumber(milestoneLevel, 0, 1000)

        await trainer.save()

        res.json({ ok: true, trainer })
    } catch (error) {
        console.error('PUT /api/admin/battle-trainers/:id error:', error)
        res.status(500).json({ ok: false, message: error.message })
    }
})

// POST /api/admin/battle-trainers/auto-generate
router.post('/auto-generate', async (req, res) => {
    try {
        const startLevel = parsePositiveInt(req.body?.startLevel, 1)
        const maxLevel = Math.max(startLevel, parsePositiveInt(req.body?.maxLevel, startLevel))
        const step = parsePositiveInt(req.body?.step, 10)
        const teamSize = clampNumber(req.body?.teamSize, 1, 6)
        const configuredCoinsReward = parseOptionalRewardNumber(req.body?.platinumCoinsReward)
        const configuredExpReward = parseOptionalRewardNumber(req.body?.expReward)
        const autoImageUrl = String(req.body?.imageUrl || '').trim()
        const requestedImageUrls = Array.isArray(req.body?.imageUrls) ? req.body.imageUrls : []
        const autoImagePool = requestedImageUrls
            .map((entry) => String(entry || '').trim())
            .filter(Boolean)
        if (autoImagePool.length === 0 && autoImageUrl) {
            autoImagePool.push(autoImageUrl)
        }

        const pokemonPool = await Pokemon.find({})
            .select('_id name pokedexNumber defaultFormId forms')
            .sort({ pokedexNumber: 1, _id: 1 })
            .lean()

        if (!Array.isArray(pokemonPool) || pokemonPool.length === 0) {
            return res.status(400).json({ ok: false, message: 'Không có Pokemon để tạo đội hình trainer tự động' })
        }

        const levelSet = new Set([startLevel])
        for (let level = step; level <= maxLevel; level += step) {
            if (level >= startLevel) {
                levelSet.add(level)
            }
        }
        const levels = [...levelSet].sort((a, b) => a - b)

        await normalizeAutoTrainerMoonPointsRewards()

        const upsertResults = await Promise.all(
            levels.map(async (level, index) => {
                const rewardValue = Math.max(10, level * 10)
                const platinumCoinsReward = configuredCoinsReward !== null ? configuredCoinsReward : rewardValue
                const expReward = configuredExpReward !== null ? configuredExpReward : rewardValue
                const team = buildAutoTeam(pokemonPool, level, index * 17 + level, teamSize)
                const trainerPatch = {
                    name: `HLV Mốc Lv ${level}`,
                    quote: `Vượt qua mốc sức mạnh cấp ${level}!`,
                    isActive: true,
                    orderIndex: level,
                    team,
                    prizePokemonId: null,
                    prizePokemonFormId: 'normal',
                    prizePokemonLevel: 0,
                    prizeItemId: null,
                    prizeItemQuantity: 1,
                    platinumCoinsReward,
                    expReward,
                    moonPointsReward: 0,
                    autoGenerated: true,
                    milestoneLevel: level,
                }

                if (autoImagePool.length > 0) {
                    trainerPatch.imageUrl = autoImagePool[index % autoImagePool.length]
                }

                const trainerDoc = await BattleTrainer.findOneAndUpdate(
                    {
                        autoGenerated: true,
                        milestoneLevel: level,
                    },
                    {
                        $set: trainerPatch,
                    },
                    {
                        new: true,
                        upsert: true,
                    }
                ).lean()
                return trainerDoc
            })
        )

        res.json({
            ok: true,
            message: `Đã tạo/cập nhật ${upsertResults.length} trainer theo mốc cấp`,
            generatedCount: upsertResults.length,
            levels,
            trainers: upsertResults,
        })
    } catch (error) {
        console.error('POST /api/admin/battle-trainers/auto-generate error:', error)
        res.status(500).json({ ok: false, message: error.message })
    }
})

// DELETE /api/admin/battle-trainers
router.delete('/', async (_req, res) => {
    try {
        const result = await BattleTrainer.deleteMany({})
        const deletedCount = Math.max(0, Number(result?.deletedCount) || 0)
        res.json({
            ok: true,
            message: `Đã xóa ${deletedCount} huấn luyện viên`,
            deletedCount,
        })
    } catch (error) {
        console.error('DELETE /api/admin/battle-trainers error:', error)
        res.status(500).json({ ok: false, message: 'Lỗi máy chủ' })
    }
})

// DELETE /api/admin/battle-trainers/auto-generated
router.delete('/auto-generated', async (_req, res) => {
    try {
        const result = await BattleTrainer.deleteMany({ autoGenerated: true })
        const deletedCount = Math.max(0, Number(result?.deletedCount) || 0)
        res.json({
            ok: true,
            message: `Đã xóa ${deletedCount} trainer auto-generated`,
            deletedCount,
        })
    } catch (error) {
        console.error('DELETE /api/admin/battle-trainers/auto-generated error:', error)
        res.status(500).json({ ok: false, message: 'Lỗi máy chủ' })
    }
})

// DELETE /api/admin/battle-trainers/:id
router.delete('/:id', async (req, res) => {
    try {
        const trainer = await BattleTrainer.findById(req.params.id)
        if (!trainer) {
            return res.status(404).json({ ok: false, message: 'Không tìm thấy huấn luyện viên' })
        }
        await trainer.deleteOne()
        res.json({ ok: true, message: 'Đã xóa huấn luyện viên' })
    } catch (error) {
        console.error('DELETE /api/admin/battle-trainers/:id error:', error)
        res.status(500).json({ ok: false, message: 'Lỗi máy chủ' })
    }
})

export default router
